version: '3.8'

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
