/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { AccountResponse } from './AccountResponse';
import {
    AccountResponseFromJSON,
    AccountResponseFromJSONTyped,
    AccountResponseToJSON,
} from './AccountResponse';

/**
 * 
 * @export
 * @interface AccountResponseResult
 */
export interface AccountResponseResult {
    /**
     * 
     * @type {AccountResponse}
     * @memberof AccountResponseResult
     */
    data?: AccountResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof AccountResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountResponseResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the AccountResponseResult interface.
 */
export function instanceOfAccountResponseResult(value: object): value is AccountResponseResult {
    return true;
}

export function AccountResponseResultFromJSON(json: any): AccountResponseResult {
    return AccountResponseResultFromJSONTyped(json, false);
}

export function AccountResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AccountResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function AccountResponseResultToJSON(value?: AccountResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': AccountResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

