/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FashionItemStatus } from './FashionItemStatus';
import {
    FashionItemStatusFromJSON,
    FashionItemStatusFromJSONTyped,
    FashionItemStatusToJSON,
} from './FashionItemStatus';
import type { FashionItemType } from './FashionItemType';
import {
    FashionItemTypeFromJSON,
    FashionItemTypeFromJSONTyped,
    FashionItemTypeToJSON,
} from './FashionItemType';
import type { ShopDetailResponse } from './ShopDetailResponse';
import {
    ShopDetailResponseFromJSON,
    ShopDetailResponseFromJSONTyped,
    ShopDetailResponseToJSON,
} from './ShopDetailResponse';

/**
 * 
 * @export
 * @interface AuctionFashionItemDetailResponse
 */
export interface AuctionFashionItemDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof AuctionFashionItemDetailResponse
     */
    itemId?: string;
    /**
     * 
     * @type {FashionItemType}
     * @memberof AuctionFashionItemDetailResponse
     */
    type?: FashionItemType;
    /**
     * 
     * @type {number}
     * @memberof AuctionFashionItemDetailResponse
     */
    sellingPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof AuctionFashionItemDetailResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionFashionItemDetailResponse
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof AuctionFashionItemDetailResponse
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof AuctionFashionItemDetailResponse
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof AuctionFashionItemDetailResponse
     */
    condition?: string;
    /**
     * 
     * @type {number}
     * @memberof AuctionFashionItemDetailResponse
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof AuctionFashionItemDetailResponse
     */
    initialPrice?: number;
    /**
     * 
     * @type {FashionItemStatus}
     * @memberof AuctionFashionItemDetailResponse
     */
    auctionItemStatus?: FashionItemStatus;
    /**
     * 
     * @type {string}
     * @memberof AuctionFashionItemDetailResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionFashionItemDetailResponse
     */
    categoryId?: string;
    /**
     * 
     * @type {ShopDetailResponse}
     * @memberof AuctionFashionItemDetailResponse
     */
    shop?: ShopDetailResponse;
}

/**
 * Check if a given object implements the AuctionFashionItemDetailResponse interface.
 */
export function instanceOfAuctionFashionItemDetailResponse(value: object): value is AuctionFashionItemDetailResponse {
    return true;
}

export function AuctionFashionItemDetailResponseFromJSON(json: any): AuctionFashionItemDetailResponse {
    return AuctionFashionItemDetailResponseFromJSONTyped(json, false);
}

export function AuctionFashionItemDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuctionFashionItemDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'type': json['type'] == null ? undefined : FashionItemTypeFromJSON(json['type']),
        'sellingPrice': json['sellingPrice'] == null ? undefined : json['sellingPrice'],
        'name': json['name'] == null ? undefined : json['name'],
        'note': json['note'] == null ? undefined : json['note'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'value': json['value'] == null ? undefined : json['value'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'initialPrice': json['initialPrice'] == null ? undefined : json['initialPrice'],
        'auctionItemStatus': json['auctionItemStatus'] == null ? undefined : FashionItemStatusFromJSON(json['auctionItemStatus']),
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'shop': json['shop'] == null ? undefined : ShopDetailResponseFromJSON(json['shop']),
    };
}

export function AuctionFashionItemDetailResponseToJSON(value?: AuctionFashionItemDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'itemId': value['itemId'],
        'type': FashionItemTypeToJSON(value['type']),
        'sellingPrice': value['sellingPrice'],
        'name': value['name'],
        'note': value['note'],
        'quantity': value['quantity'],
        'value': value['value'],
        'condition': value['condition'],
        'duration': value['duration'],
        'initialPrice': value['initialPrice'],
        'auctionItemStatus': FashionItemStatusToJSON(value['auctionItemStatus']),
        'shopId': value['shopId'],
        'categoryId': value['categoryId'],
        'shop': ShopDetailResponseToJSON(value['shop']),
    };
}

