/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberDetailResponse } from './MemberDetailResponse';
import {
    MemberDetailResponseFromJSON,
    MemberDetailResponseFromJSONTyped,
    MemberDetailResponseToJSON,
} from './MemberDetailResponse';
import type { TransactionDetailResponse } from './TransactionDetailResponse';
import {
    TransactionDetailResponseFromJSON,
    TransactionDetailResponseFromJSONTyped,
    TransactionDetailResponseToJSON,
} from './TransactionDetailResponse';

/**
 * 
 * @export
 * @interface AuctionDepositDetailResponse
 */
export interface AuctionDepositDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof AuctionDepositDetailResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionDepositDetailResponse
     */
    auctionId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionDepositDetailResponse
     */
    memberId?: string;
    /**
     * 
     * @type {MemberDetailResponse}
     * @memberof AuctionDepositDetailResponse
     */
    member?: MemberDetailResponse;
    /**
     * 
     * @type {number}
     * @memberof AuctionDepositDetailResponse
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof AuctionDepositDetailResponse
     */
    transactionId?: string;
    /**
     * 
     * @type {TransactionDetailResponse}
     * @memberof AuctionDepositDetailResponse
     */
    transaction?: TransactionDetailResponse;
    /**
     * 
     * @type {Date}
     * @memberof AuctionDepositDetailResponse
     */
    createdDate?: Date;
}

/**
 * Check if a given object implements the AuctionDepositDetailResponse interface.
 */
export function instanceOfAuctionDepositDetailResponse(value: object): value is AuctionDepositDetailResponse {
    return true;
}

export function AuctionDepositDetailResponseFromJSON(json: any): AuctionDepositDetailResponse {
    return AuctionDepositDetailResponseFromJSONTyped(json, false);
}

export function AuctionDepositDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuctionDepositDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'auctionId': json['auctionId'] == null ? undefined : json['auctionId'],
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'member': json['member'] == null ? undefined : MemberDetailResponseFromJSON(json['member']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'transaction': json['transaction'] == null ? undefined : TransactionDetailResponseFromJSON(json['transaction']),
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
    };
}

export function AuctionDepositDetailResponseToJSON(value?: AuctionDepositDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'auctionId': value['auctionId'],
        'memberId': value['memberId'],
        'member': MemberDetailResponseToJSON(value['member']),
        'amount': value['amount'],
        'transactionId': value['transactionId'],
        'transaction': TransactionDetailResponseToJSON(value['transaction']),
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
    };
}

