/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuctionListResponse
 */
export interface AuctionListResponse {
    /**
     * 
     * @type {string}
     * @memberof AuctionListResponse
     */
    auctionId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionListResponse
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof AuctionListResponse
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AuctionListResponse
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof AuctionListResponse
     */
    depositFee?: number;
    /**
     * 
     * @type {string}
     * @memberof AuctionListResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionListResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuctionListResponse
     */
    auctionItemId?: string;
}

/**
 * Check if a given object implements the AuctionListResponse interface.
 */
export function instanceOfAuctionListResponse(value: object): value is AuctionListResponse {
    return true;
}

export function AuctionListResponseFromJSON(json: any): AuctionListResponse {
    return AuctionListResponseFromJSONTyped(json, false);
}

export function AuctionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuctionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'auctionId': json['auctionId'] == null ? undefined : json['auctionId'],
        'title': json['title'] == null ? undefined : json['title'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'depositFee': json['depositFee'] == null ? undefined : json['depositFee'],
        'status': json['status'] == null ? undefined : json['status'],
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'auctionItemId': json['auctionItemId'] == null ? undefined : json['auctionItemId'],
    };
}

export function AuctionListResponseToJSON(value?: AuctionListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'auctionId': value['auctionId'],
        'title': value['title'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'depositFee': value['depositFee'],
        'status': value['status'],
        'shopId': value['shopId'],
        'auctionItemId': value['auctionItemId'],
    };
}

