/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BidListResponse } from './BidListResponse';
import {
    BidListResponseFromJSON,
    BidListResponseFromJSONTyped,
    BidListResponseToJSON,
} from './BidListResponse';

/**
 * 
 * @export
 * @interface BidListResponsePaginationResponse
 */
export interface BidListResponsePaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof BidListResponsePaginationResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof BidListResponsePaginationResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof BidListResponsePaginationResponse
     */
    searchTerm?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BidListResponsePaginationResponse
     */
    filters?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BidListResponsePaginationResponse
     */
    orderBy?: string;
    /**
     * 
     * @type {number}
     * @memberof BidListResponsePaginationResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BidListResponsePaginationResponse
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BidListResponsePaginationResponse
     */
    readonly hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BidListResponsePaginationResponse
     */
    readonly hasPrevious?: boolean;
    /**
     * 
     * @type {Array<BidListResponse>}
     * @memberof BidListResponsePaginationResponse
     */
    items?: Array<BidListResponse>;
}

/**
 * Check if a given object implements the BidListResponsePaginationResponse interface.
 */
export function instanceOfBidListResponsePaginationResponse(value: object): value is BidListResponsePaginationResponse {
    return true;
}

export function BidListResponsePaginationResponseFromJSON(json: any): BidListResponsePaginationResponse {
    return BidListResponsePaginationResponseFromJSONTyped(json, false);
}

export function BidListResponsePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BidListResponsePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(BidListResponseFromJSON)),
    };
}

export function BidListResponsePaginationResponseToJSON(value?: Omit<BidListResponsePaginationResponse, 'totalPages'|'hasNext'|'hasPrevious'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'searchTerm': value['searchTerm'],
        'filters': value['filters'],
        'orderBy': value['orderBy'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(BidListResponseToJSON)),
    };
}

