/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryRequest
 */
export interface CategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CategoryRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CategoryRequest interface.
 */
export function instanceOfCategoryRequest(value: object): value is CategoryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CategoryRequestFromJSON(json: any): CategoryRequest {
    return CategoryRequestFromJSONTyped(json, false);
}

export function CategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CategoryRequestToJSON(value?: CategoryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

