/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';

/**
 * 
 * @export
 * @interface CategoryResult
 */
export interface CategoryResult {
    /**
     * 
     * @type {Category}
     * @memberof CategoryResult
     */
    data?: Category;
    /**
     * 
     * @type {ResultStatus}
     * @memberof CategoryResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof CategoryResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the CategoryResult interface.
 */
export function instanceOfCategoryResult(value: object): value is CategoryResult {
    return true;
}

export function CategoryResultFromJSON(json: any): CategoryResult {
    return CategoryResultFromJSONTyped(json, false);
}

export function CategoryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CategoryFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function CategoryResultToJSON(value?: CategoryResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': CategoryToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

