/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';

/**
 * 
 * @export
 * @interface CategoryListResult
 */
export interface CategoryListResult {
    /**
     * 
     * @type {Array<Category>}
     * @memberof CategoryListResult
     */
    data?: Array<Category> | null;
    /**
     * 
     * @type {ResultStatus}
     * @memberof CategoryListResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof CategoryListResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the CategoryListResult interface.
 */
export function instanceOfCategoryListResult(value: object): value is CategoryListResult {
    return true;
}

export function CategoryListResultFromJSON(json: any): CategoryListResult {
    return CategoryListResultFromJSONTyped(json, false);
}

export function CategoryListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CategoryFromJSON)),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function CategoryListResultToJSON(value?: CategoryListResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CategoryToJSON)),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

