/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CategoryStatus = {
  Available: "Available",
  Unavailable: "Unavailable",
  Special: "Special",
} as const;
export type CategoryStatus =
  (typeof CategoryStatus)[keyof typeof CategoryStatus];

export function CategoryStatusFromJSON(json: any): CategoryStatus {
  return CategoryStatusFromJSONTyped(json, false);
}

export function CategoryStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryStatus {
  return json as CategoryStatus;
}

export function CategoryStatusToJSON(value?: CategoryStatus | null): any {
  return value as any;
}
