/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsignSaleDetailResponse } from './ConsignSaleDetailResponse';
import {
    ConsignSaleDetailResponseFromJSON,
    ConsignSaleDetailResponseFromJSONTyped,
    ConsignSaleDetailResponseToJSON,
} from './ConsignSaleDetailResponse';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';

/**
 * 
 * @export
 * @interface ConsignSaleDetailResponseListResult
 */
export interface ConsignSaleDetailResponseListResult {
    /**
     * 
     * @type {Array<ConsignSaleDetailResponse>}
     * @memberof ConsignSaleDetailResponseListResult
     */
    data?: Array<ConsignSaleDetailResponse> | null;
    /**
     * 
     * @type {ResultStatus}
     * @memberof ConsignSaleDetailResponseListResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConsignSaleDetailResponseListResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the ConsignSaleDetailResponseListResult interface.
 */
export function instanceOfConsignSaleDetailResponseListResult(value: object): value is ConsignSaleDetailResponseListResult {
    return true;
}

export function ConsignSaleDetailResponseListResultFromJSON(json: any): ConsignSaleDetailResponseListResult {
    return ConsignSaleDetailResponseListResultFromJSONTyped(json, false);
}

export function ConsignSaleDetailResponseListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleDetailResponseListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ConsignSaleDetailResponseFromJSON)),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function ConsignSaleDetailResponseListResultToJSON(value?: ConsignSaleDetailResponseListResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ConsignSaleDetailResponseToJSON)),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

