/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ConsignSaleType = {
    ConsignedForSale: 'ConsignedForSale',
    ConsignedForAuction: 'ConsignedForAuction',
    ForSale: 'ForSale'
} as const;
export type ConsignSaleType = typeof ConsignSaleType[keyof typeof ConsignSaleType];


export function instanceOfConsignSaleType(value: any): boolean {
    for (const key in ConsignSaleType) {
        if (Object.prototype.hasOwnProperty.call(ConsignSaleType, key)) {
            if ((ConsignSaleType as Record<string, ConsignSaleType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConsignSaleTypeFromJSON(json: any): ConsignSaleType {
    return ConsignSaleTypeFromJSONTyped(json, false);
}

export function ConsignSaleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleType {
    return json as ConsignSaleType;
}

export function ConsignSaleTypeToJSON(value?: ConsignSaleType | null): any {
    return value as any;
}

