/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ConsignSaleMethod = {
    Online: 'Online',
    Offline: 'Offline'
} as const;
export type ConsignSaleMethod = typeof ConsignSaleMethod[keyof typeof ConsignSaleMethod];


export function instanceOfConsignSaleMethod(value: any): boolean {
    for (const key in ConsignSaleMethod) {
        if (Object.prototype.hasOwnProperty.call(ConsignSaleMethod, key)) {
            if ((ConsignSaleMethod as Record<string, ConsignSaleMethod>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConsignSaleMethodFromJSON(json: any): ConsignSaleMethod {
    return ConsignSaleMethodFromJSONTyped(json, false);
}

export function ConsignSaleMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleMethod {
    return json as ConsignSaleMethod;
}

export function ConsignSaleMethodToJSON(value?: ConsignSaleMethod | null): any {
    return value as any;
}

