/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FashionItemDetailResponse } from './FashionItemDetailResponse';
import {
    FashionItemDetailResponseFromJSON,
    FashionItemDetailResponseFromJSONTyped,
    FashionItemDetailResponseToJSON,
} from './FashionItemDetailResponse';

/**
 * 
 * @export
 * @interface ConsignSaleDetailResponse
 */
export interface ConsignSaleDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetailResponse
     */
    consignSaleDetailId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetailResponse
     */
    consignSaleId?: string;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleDetailResponse
     */
    dealPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleDetailResponse
     */
    confirmedPrice?: number;
    /**
     * 
     * @type {FashionItemDetailResponse}
     * @memberof ConsignSaleDetailResponse
     */
    fashionItem?: FashionItemDetailResponse;
}

/**
 * Check if a given object implements the ConsignSaleDetailResponse interface.
 */
export function instanceOfConsignSaleDetailResponse(value: object): value is ConsignSaleDetailResponse {
    return true;
}

export function ConsignSaleDetailResponseFromJSON(json: any): ConsignSaleDetailResponse {
    return ConsignSaleDetailResponseFromJSONTyped(json, false);
}

export function ConsignSaleDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'consignSaleDetailId': json['consignSaleDetailId'] == null ? undefined : json['consignSaleDetailId'],
        'consignSaleId': json['consignSaleId'] == null ? undefined : json['consignSaleId'],
        'dealPrice': json['dealPrice'] == null ? undefined : json['dealPrice'],
        'confirmedPrice': json['confirmedPrice'] == null ? undefined : json['confirmedPrice'],
        'fashionItem': json['fashionItem'] == null ? undefined : FashionItemDetailResponseFromJSON(json['fashionItem']),
    };
}

export function ConsignSaleDetailResponseToJSON(value?: ConsignSaleDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'consignSaleDetailId': value['consignSaleDetailId'],
        'consignSaleId': value['consignSaleId'],
        'dealPrice': value['dealPrice'],
        'confirmedPrice': value['confirmedPrice'],
        'fashionItem': FashionItemDetailResponseToJSON(value['fashionItem']),
    };
}

