/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsignSaleDetailResponse2
 */
export interface ConsignSaleDetailResponse2 {
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetailResponse2
     */
    consignSaleDetailId?: string;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleDetailResponse2
     */
    dealPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleDetailResponse2
     */
    confirmedPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetailResponse2
     */
    itemName?: string | null;
}

/**
 * Check if a given object implements the ConsignSaleDetailResponse2 interface.
 */
export function instanceOfConsignSaleDetailResponse2(value: object): value is ConsignSaleDetailResponse2 {
    return true;
}

export function ConsignSaleDetailResponse2FromJSON(json: any): ConsignSaleDetailResponse2 {
    return ConsignSaleDetailResponse2FromJSONTyped(json, false);
}

export function ConsignSaleDetailResponse2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleDetailResponse2 {
    if (json == null) {
        return json;
    }
    return {
        
        'consignSaleDetailId': json['consignSaleDetailId'] == null ? undefined : json['consignSaleDetailId'],
        'dealPrice': json['dealPrice'] == null ? undefined : json['dealPrice'],
        'confirmedPrice': json['confirmedPrice'] == null ? undefined : json['confirmedPrice'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
    };
}

export function ConsignSaleDetailResponse2ToJSON(value?: ConsignSaleDetailResponse2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'consignSaleDetailId': value['consignSaleDetailId'],
        'dealPrice': value['dealPrice'],
        'confirmedPrice': value['confirmedPrice'],
        'itemName': value['itemName'],
    };
}

