/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsignSaleMethod } from './ConsignSaleMethod';
import {
    ConsignSaleMethodFromJSON,
    ConsignSaleMethodFromJSONTyped,
    ConsignSaleMethodToJSON,
} from './ConsignSaleMethod';
import type { ConsignSaleType } from './ConsignSaleType';
import {
    ConsignSaleTypeFromJSON,
    ConsignSaleTypeFromJSONTyped,
    ConsignSaleTypeToJSON,
} from './ConsignSaleType';
import type { ConsignSaleDetailResponse2 } from './ConsignSaleDetailResponse2';
import {
    ConsignSaleDetailResponse2FromJSON,
    ConsignSaleDetailResponse2FromJSONTyped,
    ConsignSaleDetailResponse2ToJSON,
} from './ConsignSaleDetailResponse2';
import type { ConsignSaleStatus } from './ConsignSaleStatus';
import {
    ConsignSaleStatusFromJSON,
    ConsignSaleStatusFromJSONTyped,
    ConsignSaleStatusToJSON,
} from './ConsignSaleStatus';

/**
 * 
 * @export
 * @interface ConsignSaleResponse
 */
export interface ConsignSaleResponse {
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    consignSaleId?: string;
    /**
     * 
     * @type {ConsignSaleType}
     * @memberof ConsignSaleResponse
     */
    type?: ConsignSaleType;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    consignSaleCode?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ConsignSaleResponse
     */
    createdDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleResponse
     */
    consignDuration?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ConsignSaleResponse
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ConsignSaleResponse
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    memberId?: string | null;
    /**
     * 
     * @type {ConsignSaleStatus}
     * @memberof ConsignSaleResponse
     */
    status?: ConsignSaleStatus;
    /**
     * 
     * @type {ConsignSaleMethod}
     * @memberof ConsignSaleResponse
     */
    consignSaleMethod?: ConsignSaleMethod;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleResponse
     */
    totalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleResponse
     */
    soldPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleResponse
     */
    memberReceivedAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    consginer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleResponse
     */
    email?: string | null;
    /**
     * 
     * @type {Array<ConsignSaleDetailResponse2>}
     * @memberof ConsignSaleResponse
     */
    consignSaleDetails?: Array<ConsignSaleDetailResponse2> | null;
}

/**
 * Check if a given object implements the ConsignSaleResponse interface.
 */
export function instanceOfConsignSaleResponse(value: object): value is ConsignSaleResponse {
    return true;
}

export function ConsignSaleResponseFromJSON(json: any): ConsignSaleResponse {
    return ConsignSaleResponseFromJSONTyped(json, false);
}

export function ConsignSaleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'consignSaleId': json['consignSaleId'] == null ? undefined : json['consignSaleId'],
        'type': json['type'] == null ? undefined : ConsignSaleTypeFromJSON(json['type']),
        'consignSaleCode': json['consignSaleCode'] == null ? undefined : json['consignSaleCode'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'consignDuration': json['consignDuration'] == null ? undefined : json['consignDuration'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'status': json['status'] == null ? undefined : ConsignSaleStatusFromJSON(json['status']),
        'consignSaleMethod': json['consignSaleMethod'] == null ? undefined : ConsignSaleMethodFromJSON(json['consignSaleMethod']),
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
        'soldPrice': json['soldPrice'] == null ? undefined : json['soldPrice'],
        'memberReceivedAmount': json['memberReceivedAmount'] == null ? undefined : json['memberReceivedAmount'],
        'consginer': json['consginer'] == null ? undefined : json['consginer'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'email': json['email'] == null ? undefined : json['email'],
        'consignSaleDetails': json['consignSaleDetails'] == null ? undefined : ((json['consignSaleDetails'] as Array<any>).map(ConsignSaleDetailResponse2FromJSON)),
    };
}

export function ConsignSaleResponseToJSON(value?: ConsignSaleResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'consignSaleId': value['consignSaleId'],
        'type': ConsignSaleTypeToJSON(value['type']),
        'consignSaleCode': value['consignSaleCode'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'consignDuration': value['consignDuration'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'shopId': value['shopId'],
        'memberId': value['memberId'],
        'status': ConsignSaleStatusToJSON(value['status']),
        'consignSaleMethod': ConsignSaleMethodToJSON(value['consignSaleMethod']),
        'totalPrice': value['totalPrice'],
        'soldPrice': value['soldPrice'],
        'memberReceivedAmount': value['memberReceivedAmount'],
        'consginer': value['consginer'],
        'phone': value['phone'],
        'address': value['address'],
        'email': value['email'],
        'consignSaleDetails': value['consignSaleDetails'] == null ? undefined : ((value['consignSaleDetails'] as Array<any>).map(ConsignSaleDetailResponse2ToJSON)),
    };
}

