/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { ConsignSaleResponsePaginationResponse } from './ConsignSaleResponsePaginationResponse';
import {
    ConsignSaleResponsePaginationResponseFromJSON,
    ConsignSaleResponsePaginationResponseFromJSONTyped,
    ConsignSaleResponsePaginationResponseToJSON,
} from './ConsignSaleResponsePaginationResponse';

/**
 * 
 * @export
 * @interface ConsignSaleResponsePaginationResponseResult
 */
export interface ConsignSaleResponsePaginationResponseResult {
    /**
     * 
     * @type {ConsignSaleResponsePaginationResponse}
     * @memberof ConsignSaleResponsePaginationResponseResult
     */
    data?: ConsignSaleResponsePaginationResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof ConsignSaleResponsePaginationResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConsignSaleResponsePaginationResponseResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the ConsignSaleResponsePaginationResponseResult interface.
 */
export function instanceOfConsignSaleResponsePaginationResponseResult(value: object): value is ConsignSaleResponsePaginationResponseResult {
    return true;
}

export function ConsignSaleResponsePaginationResponseResultFromJSON(json: any): ConsignSaleResponsePaginationResponseResult {
    return ConsignSaleResponsePaginationResponseResultFromJSONTyped(json, false);
}

export function ConsignSaleResponsePaginationResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleResponsePaginationResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ConsignSaleResponsePaginationResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function ConsignSaleResponsePaginationResponseResultToJSON(value?: ConsignSaleResponsePaginationResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ConsignSaleResponsePaginationResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

