/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FashionItem } from './FashionItem';
import {
    FashionItemFromJSON,
    FashionItemFromJSONTyped,
    FashionItemToJSON,
} from './FashionItem';
import type { ConsignSale } from './ConsignSale';
import {
    ConsignSaleFromJSON,
    ConsignSaleFromJSONTyped,
    ConsignSaleToJSON,
} from './ConsignSale';

/**
 * 
 * @export
 * @interface ConsignSaleDetail
 */
export interface ConsignSaleDetail {
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetail
     */
    consignSaleDetailId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetail
     */
    consignSaleId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsignSaleDetail
     */
    fashionItemId?: string;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleDetail
     */
    dealPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ConsignSaleDetail
     */
    confirmedPrice?: number;
    /**
     * 
     * @type {ConsignSale}
     * @memberof ConsignSaleDetail
     */
    consignSale?: ConsignSale;
    /**
     * 
     * @type {FashionItem}
     * @memberof ConsignSaleDetail
     */
    fashionItem?: FashionItem;
}

/**
 * Check if a given object implements the ConsignSaleDetail interface.
 */
export function instanceOfConsignSaleDetail(value: object): value is ConsignSaleDetail {
    return true;
}

export function ConsignSaleDetailFromJSON(json: any): ConsignSaleDetail {
    return ConsignSaleDetailFromJSONTyped(json, false);
}

export function ConsignSaleDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignSaleDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'consignSaleDetailId': json['consignSaleDetailId'] == null ? undefined : json['consignSaleDetailId'],
        'consignSaleId': json['consignSaleId'] == null ? undefined : json['consignSaleId'],
        'fashionItemId': json['fashionItemId'] == null ? undefined : json['fashionItemId'],
        'dealPrice': json['dealPrice'] == null ? undefined : json['dealPrice'],
        'confirmedPrice': json['confirmedPrice'] == null ? undefined : json['confirmedPrice'],
        'consignSale': json['consignSale'] == null ? undefined : ConsignSaleFromJSON(json['consignSale']),
        'fashionItem': json['fashionItem'] == null ? undefined : FashionItemFromJSON(json['fashionItem']),
    };
}

export function ConsignSaleDetailToJSON(value?: ConsignSaleDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'consignSaleDetailId': value['consignSaleDetailId'],
        'consignSaleId': value['consignSaleId'],
        'fashionItemId': value['fashionItemId'],
        'dealPrice': value['dealPrice'],
        'confirmedPrice': value['confirmedPrice'],
        'consignSale': ConsignSaleToJSON(value['consignSale']),
        'fashionItem': FashionItemToJSON(value['fashionItem']),
    };
}

