/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsignSaleType } from './ConsignSaleType';
import {
    ConsignSaleTypeFromJSON,
    ConsignSaleTypeFromJSONTyped,
    ConsignSaleTypeToJSON,
} from './ConsignSaleType';
import type { AddFashionItemForConsignRequest } from './AddFashionItemForConsignRequest';
import {
    AddFashionItemForConsignRequestFromJSON,
    AddFashionItemForConsignRequestFromJSONTyped,
    AddFashionItemForConsignRequestToJSON,
} from './AddFashionItemForConsignRequest';

/**
 * 
 * @export
 * @interface CreateConsignSaleRequest
 */
export interface CreateConsignSaleRequest {
    /**
     * 
     * @type {ConsignSaleType}
     * @memberof CreateConsignSaleRequest
     */
    type?: ConsignSaleType;
    /**
     * 
     * @type {string}
     * @memberof CreateConsignSaleRequest
     */
    shopId?: string;
    /**
     * 
     * @type {Array<AddFashionItemForConsignRequest>}
     * @memberof CreateConsignSaleRequest
     */
    fashionItemForConsigns?: Array<AddFashionItemForConsignRequest> | null;
}

/**
 * Check if a given object implements the CreateConsignSaleRequest interface.
 */
export function instanceOfCreateConsignSaleRequest(value: object): value is CreateConsignSaleRequest {
    return true;
}

export function CreateConsignSaleRequestFromJSON(json: any): CreateConsignSaleRequest {
    return CreateConsignSaleRequestFromJSONTyped(json, false);
}

export function CreateConsignSaleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConsignSaleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : ConsignSaleTypeFromJSON(json['type']),
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'fashionItemForConsigns': json['fashionItemForConsigns'] == null ? undefined : ((json['fashionItemForConsigns'] as Array<any>).map(AddFashionItemForConsignRequestFromJSON)),
    };
}

export function CreateConsignSaleRequestToJSON(value?: CreateConsignSaleRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': ConsignSaleTypeToJSON(value['type']),
        'shopId': value['shopId'],
        'fashionItemForConsigns': value['fashionItemForConsigns'] == null ? undefined : ((value['fashionItemForConsigns'] as Array<any>).map(AddFashionItemForConsignRequestToJSON)),
    };
}

