/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWithdrawRequest
 */
export interface CreateWithdrawRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateWithdrawRequest
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateWithdrawRequest
     */
    bank?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateWithdrawRequest
     */
    bankAccountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateWithdrawRequest
     */
    bankAccountName?: string | null;
}

/**
 * Check if a given object implements the CreateWithdrawRequest interface.
 */
export function instanceOfCreateWithdrawRequest(value: object): value is CreateWithdrawRequest {
    return true;
}

export function CreateWithdrawRequestFromJSON(json: any): CreateWithdrawRequest {
    return CreateWithdrawRequestFromJSONTyped(json, false);
}

export function CreateWithdrawRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWithdrawRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'bank': json['bank'] == null ? undefined : json['bank'],
        'bankAccountNumber': json['bankAccountNumber'] == null ? undefined : json['bankAccountNumber'],
        'bankAccountName': json['bankAccountName'] == null ? undefined : json['bankAccountName'],
    };
}

export function CreateWithdrawRequestToJSON(value?: CreateWithdrawRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'bank': value['bank'],
        'bankAccountNumber': value['bankAccountNumber'],
        'bankAccountName': value['bankAccountName'],
    };
}

