/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInquiryResponse
 */
export interface CreateInquiryResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    inquiryId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateInquiryResponse
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    fullname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInquiryResponse
     */
    memberId?: string;
}

/**
 * Check if a given object implements the CreateInquiryResponse interface.
 */
export function instanceOfCreateInquiryResponse(value: object): value is CreateInquiryResponse {
    return true;
}

export function CreateInquiryResponseFromJSON(json: any): CreateInquiryResponse {
    return CreateInquiryResponseFromJSONTyped(json, false);
}

export function CreateInquiryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInquiryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'inquiryId': json['inquiryId'] == null ? undefined : json['inquiryId'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'message': json['message'] == null ? undefined : json['message'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullname': json['fullname'] == null ? undefined : json['fullname'],
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
    };
}

export function CreateInquiryResponseToJSON(value?: CreateInquiryResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inquiryId': value['inquiryId'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'message': value['message'],
        'phone': value['phone'],
        'email': value['email'],
        'fullname': value['fullname'],
        'shopId': value['shopId'],
        'memberId': value['memberId'],
    };
}

