/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsignSaleType } from './ConsignSaleType';
import {
    ConsignSaleTypeFromJSON,
    ConsignSaleTypeFromJSONTyped,
    ConsignSaleTypeToJSON,
} from './ConsignSaleType';
import type { AddFashionItemForConsignRequest } from './AddFashionItemForConsignRequest';
import {
    AddFashionItemForConsignRequestFromJSON,
    AddFashionItemForConsignRequestFromJSONTyped,
    AddFashionItemForConsignRequestToJSON,
} from './AddFashionItemForConsignRequest';

/**
 * 
 * @export
 * @interface CreateConsignSaleByShopRequest
 */
export interface CreateConsignSaleByShopRequest {
    /**
     * 
     * @type {ConsignSaleType}
     * @memberof CreateConsignSaleByShopRequest
     */
    type?: ConsignSaleType;
    /**
     * 
     * @type {string}
     * @memberof CreateConsignSaleByShopRequest
     */
    consigner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateConsignSaleByShopRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateConsignSaleByShopRequest
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateConsignSaleByShopRequest
     */
    email?: string | null;
    /**
     * 
     * @type {Array<AddFashionItemForConsignRequest>}
     * @memberof CreateConsignSaleByShopRequest
     */
    fashionItemForConsigns?: Array<AddFashionItemForConsignRequest> | null;
}

/**
 * Check if a given object implements the CreateConsignSaleByShopRequest interface.
 */
export function instanceOfCreateConsignSaleByShopRequest(value: object): value is CreateConsignSaleByShopRequest {
    return true;
}

export function CreateConsignSaleByShopRequestFromJSON(json: any): CreateConsignSaleByShopRequest {
    return CreateConsignSaleByShopRequestFromJSONTyped(json, false);
}

export function CreateConsignSaleByShopRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConsignSaleByShopRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : ConsignSaleTypeFromJSON(json['type']),
        'consigner': json['consigner'] == null ? undefined : json['consigner'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'email': json['email'] == null ? undefined : json['email'],
        'fashionItemForConsigns': json['fashionItemForConsigns'] == null ? undefined : ((json['fashionItemForConsigns'] as Array<any>).map(AddFashionItemForConsignRequestFromJSON)),
    };
}

export function CreateConsignSaleByShopRequestToJSON(value?: CreateConsignSaleByShopRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': ConsignSaleTypeToJSON(value['type']),
        'consigner': value['consigner'],
        'phone': value['phone'],
        'address': value['address'],
        'email': value['email'],
        'fashionItemForConsigns': value['fashionItemForConsigns'] == null ? undefined : ((value['fashionItemForConsigns'] as Array<any>).map(AddFashionItemForConsignRequestToJSON)),
    };
}

