/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuctionDepositRequest
 */
export interface CreateAuctionDepositRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAuctionDepositRequest
     */
    memberId: string;
}

/**
 * Check if a given object implements the CreateAuctionDepositRequest interface.
 */
export function instanceOfCreateAuctionDepositRequest(value: object): value is CreateAuctionDepositRequest {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    return true;
}

export function CreateAuctionDepositRequestFromJSON(json: any): CreateAuctionDepositRequest {
    return CreateAuctionDepositRequestFromJSONTyped(json, false);
}

export function CreateAuctionDepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuctionDepositRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'],
    };
}

export function CreateAuctionDepositRequestToJSON(value?: CreateAuctionDepositRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberId': value['memberId'],
    };
}

