/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStaffAccountRequest
 */
export interface CreateStaffAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    fullname: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    confirmPassword: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStaffAccountRequest
     */
    shopPhone: string;
}

/**
 * Check if a given object implements the CreateStaffAccountRequest interface.
 */
export function instanceOfCreateStaffAccountRequest(value: object): value is CreateStaffAccountRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullname' in value) || value['fullname'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('shopPhone' in value) || value['shopPhone'] === undefined) return false;
    return true;
}

export function CreateStaffAccountRequestFromJSON(json: any): CreateStaffAccountRequest {
    return CreateStaffAccountRequestFromJSONTyped(json, false);
}

export function CreateStaffAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStaffAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'fullname': json['fullname'],
        'phone': json['phone'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
        'address': json['address'],
        'shopPhone': json['shopPhone'],
    };
}

export function CreateStaffAccountRequestToJSON(value?: CreateStaffAccountRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'fullname': value['fullname'],
        'phone': value['phone'],
        'password': value['password'],
        'confirmPassword': value['confirmPassword'],
        'address': value['address'],
        'shopPhone': value['shopPhone'],
    };
}

