/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryRequest
 */
export interface DeliveryRequest {
    /**
     * 
     * @type {string}
     * @memberof DeliveryRequest
     */
    recipientName: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryRequest
     */
    addressType: string;
}

/**
 * Check if a given object implements the DeliveryRequest interface.
 */
export function instanceOfDeliveryRequest(value: object): value is DeliveryRequest {
    if (!('recipientName' in value) || value['recipientName'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('addressType' in value) || value['addressType'] === undefined) return false;
    return true;
}

export function DeliveryRequestFromJSON(json: any): DeliveryRequest {
    return DeliveryRequestFromJSONTyped(json, false);
}

export function DeliveryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientName': json['recipientName'],
        'phone': json['phone'],
        'address': json['address'],
        'addressType': json['addressType'],
    };
}

export function DeliveryRequestToJSON(value?: DeliveryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipientName': value['recipientName'],
        'phone': value['phone'],
        'address': value['address'],
        'addressType': value['addressType'],
    };
}

