/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { FashionItemDetailResponse } from './FashionItemDetailResponse';
import {
    FashionItemDetailResponseFromJSON,
    FashionItemDetailResponseFromJSONTyped,
    FashionItemDetailResponseToJSON,
} from './FashionItemDetailResponse';

/**
 * 
 * @export
 * @interface FashionItemDetailResponseResult
 */
export interface FashionItemDetailResponseResult {
    /**
     * 
     * @type {FashionItemDetailResponse}
     * @memberof FashionItemDetailResponseResult
     */
    data?: FashionItemDetailResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof FashionItemDetailResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof FashionItemDetailResponseResult
     */
    messages?: Array<string>;
}

/**
 * Check if a given object implements the FashionItemDetailResponseResult interface.
 */
export function instanceOfFashionItemDetailResponseResult(value: object): value is FashionItemDetailResponseResult {
    return true;
}

export function FashionItemDetailResponseResultFromJSON(json: any): FashionItemDetailResponseResult {
    return FashionItemDetailResponseResultFromJSONTyped(json, false);
}

export function FashionItemDetailResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemDetailResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FashionItemDetailResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function FashionItemDetailResponseResultToJSON(value?: FashionItemDetailResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': FashionItemDetailResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

