/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenderType } from './GenderType';
import {
    GenderTypeFromJSON,
    GenderTypeFromJSONTyped,
    GenderTypeToJSON,
} from './GenderType';
import type { SizeType } from './SizeType';
import {
    SizeTypeFromJSON,
    SizeTypeFromJSONTyped,
    SizeTypeToJSON,
} from './SizeType';

/**
 * 
 * @export
 * @interface FashionItemDetailRequest
 */
export interface FashionItemDetailRequest {
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailRequest
     */
    sellingPrice: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailRequest
     */
    note: string;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailRequest
     */
    condition: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailRequest
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailRequest
     */
    color?: string | null;
    /**
     * 
     * @type {GenderType}
     * @memberof FashionItemDetailRequest
     */
    gender?: GenderType;
    /**
     * 
     * @type {SizeType}
     * @memberof FashionItemDetailRequest
     */
    size?: SizeType;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailRequest
     */
    categoryId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FashionItemDetailRequest
     */
    images: Array<string>;
}

/**
 * Check if a given object implements the FashionItemDetailRequest interface.
 */
export function instanceOfFashionItemDetailRequest(value: object): value is FashionItemDetailRequest {
    if (!('sellingPrice' in value) || value['sellingPrice'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    return true;
}

export function FashionItemDetailRequestFromJSON(json: any): FashionItemDetailRequest {
    return FashionItemDetailRequestFromJSONTyped(json, false);
}

export function FashionItemDetailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemDetailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sellingPrice': json['sellingPrice'],
        'name': json['name'],
        'note': json['note'],
        'condition': json['condition'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'color': json['color'] == null ? undefined : json['color'],
        'gender': json['gender'] == null ? undefined : GenderTypeFromJSON(json['gender']),
        'size': json['size'] == null ? undefined : SizeTypeFromJSON(json['size']),
        'categoryId': json['categoryId'],
        'images': json['images'],
    };
}

export function FashionItemDetailRequestToJSON(value?: FashionItemDetailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sellingPrice': value['sellingPrice'],
        'name': value['name'],
        'note': value['note'],
        'condition': value['condition'],
        'brand': value['brand'],
        'color': value['color'],
        'gender': GenderTypeToJSON(value['gender']),
        'size': SizeTypeToJSON(value['size']),
        'categoryId': value['categoryId'],
        'images': value['images'],
    };
}

