/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FashionItemType = {
    ItemBase: 'ItemBase',
    ConsignedForSale: 'ConsignedForSale',
    ConsignedForAuction: 'ConsignedForAuction'
} as const;
export type FashionItemType = typeof FashionItemType[keyof typeof FashionItemType];




export function FashionItemTypeFromJSON(json: any): FashionItemType {
    return FashionItemTypeFromJSONTyped(json, false);
}

export function FashionItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemType {
    return json as FashionItemType;
}

export function FashionItemTypeToJSON(value?: FashionItemType | null): any {
    return value as any;
}

