/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Shop } from './Shop';
import {
    ShopFromJSON,
    ShopFromJSONTyped,
    ShopToJSON,
} from './Shop';
import type { FashionItemStatus } from './FashionItemStatus';
import {
    FashionItemStatusFromJSON,
    FashionItemStatusFromJSONTyped,
    FashionItemStatusToJSON,
} from './FashionItemStatus';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';
import type { FashionItemType } from './FashionItemType';
import {
    FashionItemTypeFromJSON,
    FashionItemTypeFromJSONTyped,
    FashionItemTypeToJSON,
} from './FashionItemType';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import type { ConsignSaleDetail } from './ConsignSaleDetail';
import {
    ConsignSaleDetailFromJSON,
    ConsignSaleDetailFromJSONTyped,
    ConsignSaleDetailToJSON,
} from './ConsignSaleDetail';
import type { GenderType } from './GenderType';
import {
    GenderTypeFromJSON,
    GenderTypeFromJSONTyped,
    GenderTypeToJSON,
} from './GenderType';
import type { SizeType } from './SizeType';
import {
    SizeTypeFromJSON,
    SizeTypeFromJSONTyped,
    SizeTypeToJSON,
} from './SizeType';

/**
 * 
 * @export
 * @interface FashionItem
 */
export interface FashionItem {
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    itemId?: string;
    /**
     * 
     * @type {FashionItemType}
     * @memberof FashionItem
     */
    type?: FashionItemType;
    /**
     * 
     * @type {number}
     * @memberof FashionItem
     */
    sellingPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FashionItem
     */
    condition?: number;
    /**
     * 
     * @type {ConsignSaleDetail}
     * @memberof FashionItem
     */
    consignSaleDetail?: ConsignSaleDetail;
    /**
     * 
     * @type {Shop}
     * @memberof FashionItem
     */
    shop?: Shop;
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    shopId?: string;
    /**
     * 
     * @type {Category}
     * @memberof FashionItem
     */
    category?: Category;
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    categoryId?: string | null;
    /**
     * 
     * @type {FashionItemStatus}
     * @memberof FashionItem
     */
    status?: FashionItemStatus;
    /**
     * 
     * @type {SizeType}
     * @memberof FashionItem
     */
    size?: SizeType;
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FashionItem
     */
    brand?: string | null;
    /**
     * 
     * @type {GenderType}
     * @memberof FashionItem
     */
    gender?: GenderType;
    /**
     * 
     * @type {Array<Image>}
     * @memberof FashionItem
     */
    images?: Array<Image> | null;
}

/**
 * Check if a given object implements the FashionItem interface.
 */
export function instanceOfFashionItem(value: object): value is FashionItem {
    return true;
}

export function FashionItemFromJSON(json: any): FashionItem {
    return FashionItemFromJSONTyped(json, false);
}

export function FashionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'type': json['type'] == null ? undefined : FashionItemTypeFromJSON(json['type']),
        'sellingPrice': json['sellingPrice'] == null ? undefined : json['sellingPrice'],
        'name': json['name'] == null ? undefined : json['name'],
        'note': json['note'] == null ? undefined : json['note'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'consignSaleDetail': json['consignSaleDetail'] == null ? undefined : ConsignSaleDetailFromJSON(json['consignSaleDetail']),
        'shop': json['shop'] == null ? undefined : ShopFromJSON(json['shop']),
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'category': json['category'] == null ? undefined : CategoryFromJSON(json['category']),
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'status': json['status'] == null ? undefined : FashionItemStatusFromJSON(json['status']),
        'size': json['size'] == null ? undefined : SizeTypeFromJSON(json['size']),
        'color': json['color'] == null ? undefined : json['color'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'gender': json['gender'] == null ? undefined : GenderTypeFromJSON(json['gender']),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageFromJSON)),
    };
}

export function FashionItemToJSON(value?: FashionItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'itemId': value['itemId'],
        'type': FashionItemTypeToJSON(value['type']),
        'sellingPrice': value['sellingPrice'],
        'name': value['name'],
        'note': value['note'],
        'condition': value['condition'],
        'consignSaleDetail': ConsignSaleDetailToJSON(value['consignSaleDetail']),
        'shop': ShopToJSON(value['shop']),
        'shopId': value['shopId'],
        'category': CategoryToJSON(value['category']),
        'categoryId': value['categoryId'],
        'status': FashionItemStatusToJSON(value['status']),
        'size': SizeTypeToJSON(value['size']),
        'color': value['color'],
        'brand': value['brand'],
        'gender': GenderTypeToJSON(value['gender']),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageToJSON)),
    };
}

