/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FashionItemOrderDetailResponse } from './FashionItemOrderDetailResponse';
import {
    FashionItemOrderDetailResponseFromJSON,
    FashionItemOrderDetailResponseFromJSONTyped,
    FashionItemOrderDetailResponseToJSON,
} from './FashionItemOrderDetailResponse';

/**
 * 
 * @export
 * @interface FashionItemOrderDetailResponsePaginationResponse
 */
export interface FashionItemOrderDetailResponsePaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    filters?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    orderBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    readonly hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    readonly hasPrevious?: boolean;
    /**
     * 
     * @type {Array<FashionItemOrderDetailResponse>}
     * @memberof FashionItemOrderDetailResponsePaginationResponse
     */
    items?: Array<FashionItemOrderDetailResponse> | null;
}

/**
 * Check if a given object implements the FashionItemOrderDetailResponsePaginationResponse interface.
 */
export function instanceOfFashionItemOrderDetailResponsePaginationResponse(value: object): value is FashionItemOrderDetailResponsePaginationResponse {
    return true;
}

export function FashionItemOrderDetailResponsePaginationResponseFromJSON(json: any): FashionItemOrderDetailResponsePaginationResponse {
    return FashionItemOrderDetailResponsePaginationResponseFromJSONTyped(json, false);
}

export function FashionItemOrderDetailResponsePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemOrderDetailResponsePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FashionItemOrderDetailResponseFromJSON)),
    };
}

export function FashionItemOrderDetailResponsePaginationResponseToJSON(value?: Omit<FashionItemOrderDetailResponsePaginationResponse, 'totalPages'|'hasNext'|'hasPrevious'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'searchTerm': value['searchTerm'],
        'filters': value['filters'],
        'orderBy': value['orderBy'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FashionItemOrderDetailResponseToJSON)),
    };
}

