/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FashionItemDetailResponse } from './FashionItemDetailResponse';
import {
    FashionItemDetailResponseFromJSON,
    FashionItemDetailResponseFromJSONTyped,
    FashionItemDetailResponseToJSON,
} from './FashionItemDetailResponse';

/**
 * 
 * @export
 * @interface FashionItemDetailResponsePaginationResponse
 */
export interface FashionItemDetailResponsePaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    filters?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    orderBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    readonly hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    readonly hasPrevious?: boolean;
    /**
     * 
     * @type {Array<FashionItemDetailResponse>}
     * @memberof FashionItemDetailResponsePaginationResponse
     */
    items?: Array<FashionItemDetailResponse> | null;
}

/**
 * Check if a given object implements the FashionItemDetailResponsePaginationResponse interface.
 */
export function instanceOfFashionItemDetailResponsePaginationResponse(value: object): value is FashionItemDetailResponsePaginationResponse {
    return true;
}

export function FashionItemDetailResponsePaginationResponseFromJSON(json: any): FashionItemDetailResponsePaginationResponse {
    return FashionItemDetailResponsePaginationResponseFromJSONTyped(json, false);
}

export function FashionItemDetailResponsePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemDetailResponsePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FashionItemDetailResponseFromJSON)),
    };
}

export function FashionItemDetailResponsePaginationResponseToJSON(value?: Omit<FashionItemDetailResponsePaginationResponse, 'totalPages'|'hasNext'|'hasPrevious'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'searchTerm': value['searchTerm'],
        'filters': value['filters'],
        'orderBy': value['orderBy'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FashionItemDetailResponseToJSON)),
    };
}

