/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { FashionItemOrderDetailResponsePaginationResponse } from './FashionItemOrderDetailResponsePaginationResponse';
import {
    FashionItemOrderDetailResponsePaginationResponseFromJSON,
    FashionItemOrderDetailResponsePaginationResponseFromJSONTyped,
    FashionItemOrderDetailResponsePaginationResponseToJSON,
} from './FashionItemOrderDetailResponsePaginationResponse';

/**
 * 
 * @export
 * @interface FashionItemOrderDetailResponsePaginationResponseResult
 */
export interface FashionItemOrderDetailResponsePaginationResponseResult {
    /**
     * 
     * @type {FashionItemOrderDetailResponsePaginationResponse}
     * @memberof FashionItemOrderDetailResponsePaginationResponseResult
     */
    data?: FashionItemOrderDetailResponsePaginationResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof FashionItemOrderDetailResponsePaginationResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof FashionItemOrderDetailResponsePaginationResponseResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the FashionItemOrderDetailResponsePaginationResponseResult interface.
 */
export function instanceOfFashionItemOrderDetailResponsePaginationResponseResult(value: object): value is FashionItemOrderDetailResponsePaginationResponseResult {
    return true;
}

export function FashionItemOrderDetailResponsePaginationResponseResultFromJSON(json: any): FashionItemOrderDetailResponsePaginationResponseResult {
    return FashionItemOrderDetailResponsePaginationResponseResultFromJSONTyped(json, false);
}

export function FashionItemOrderDetailResponsePaginationResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemOrderDetailResponsePaginationResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FashionItemOrderDetailResponsePaginationResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function FashionItemOrderDetailResponsePaginationResponseResultToJSON(value?: FashionItemOrderDetailResponsePaginationResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': FashionItemOrderDetailResponsePaginationResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

