/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FashionItemDetailResponse
 */
export interface FashionItemDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    itemId?: string;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponse
     */
    sellingPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponse
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponse
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    condition?: string;
    /**
     * 
     * @type {number}
     * @memberof FashionItemDetailResponse
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    shopAddress?: string;
    /**
     * 
     * @type {Date}
     * @memberof FashionItemDetailResponse
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FashionItemDetailResponse
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    consigner?: string;
    /**
     * 
     * @type {string}
     * @memberof FashionItemDetailResponse
     */
    categoryName?: string;
}

/**
 * Check if a given object implements the FashionItemDetailResponse interface.
 */
export function instanceOfFashionItemDetailResponse(value: object): value is FashionItemDetailResponse {
    return true;
}

export function FashionItemDetailResponseFromJSON(json: any): FashionItemDetailResponse {
    return FashionItemDetailResponseFromJSONTyped(json, false);
}

export function FashionItemDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'type': json['type'] == null ? undefined : json['type'],
        'sellingPrice': json['sellingPrice'] == null ? undefined : json['sellingPrice'],
        'name': json['name'] == null ? undefined : json['name'],
        'note': json['note'] == null ? undefined : json['note'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'value': json['value'] == null ? undefined : json['value'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'status': json['status'] == null ? undefined : json['status'],
        'shopAddress': json['shopAddress'] == null ? undefined : json['shopAddress'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'consigner': json['consigner'] == null ? undefined : json['consigner'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
    };
}

export function FashionItemDetailResponseToJSON(value?: FashionItemDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'itemId': value['itemId'],
        'type': value['type'],
        'sellingPrice': value['sellingPrice'],
        'name': value['name'],
        'note': value['note'],
        'quantity': value['quantity'],
        'value': value['value'],
        'condition': value['condition'],
        'duration': value['duration'],
        'status': value['status'],
        'shopAddress': value['shopAddress'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'consigner': value['consigner'],
        'categoryName': value['categoryName'],
    };
}

