/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FashionItemStatus = {
    Available: 'Available',
    Unavailable: 'Unavailable',
    OnDelivery: 'OnDelivery',
    Sold: 'Sold',
    Refundable: 'Refundable',
    Pending: 'Pending',
    PendingAuction: 'PendingAuction',
    AwaitingAuction: 'AwaitingAuction',
    Bidding: 'Bidding',
    Won: 'Won',
    Rejected: 'Rejected',
    Returned: 'Returned'
} as const;
export type FashionItemStatus = typeof FashionItemStatus[keyof typeof FashionItemStatus];


export function instanceOfFashionItemStatus(value: any): boolean {
    for (const key in FashionItemStatus) {
        if (Object.prototype.hasOwnProperty.call(FashionItemStatus, key)) {
            if ((FashionItemStatus as Record<string, FashionItemStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FashionItemStatusFromJSON(json: any): FashionItemStatus {
    return FashionItemStatusFromJSONTyped(json, false);
}

export function FashionItemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemStatus {
    return json as FashionItemStatus;
}

export function FashionItemStatusToJSON(value?: FashionItemStatus | null): any {
    return value as any;
}

