/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { FashionItemOrderDetailResponse } from './FashionItemOrderDetailResponse';
import {
    FashionItemOrderDetailResponseFromJSON,
    FashionItemOrderDetailResponseFromJSONTyped,
    FashionItemOrderDetailResponseToJSON,
} from './FashionItemOrderDetailResponse';

/**
 * 
 * @export
 * @interface FashionItemOrderDetailResponseResult
 */
export interface FashionItemOrderDetailResponseResult {
    /**
     * 
     * @type {FashionItemOrderDetailResponse}
     * @memberof FashionItemOrderDetailResponseResult
     */
    data?: FashionItemOrderDetailResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof FashionItemOrderDetailResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof FashionItemOrderDetailResponseResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the FashionItemOrderDetailResponseResult interface.
 */
export function instanceOfFashionItemOrderDetailResponseResult(value: object): value is FashionItemOrderDetailResponseResult {
    return true;
}

export function FashionItemOrderDetailResponseResultFromJSON(json: any): FashionItemOrderDetailResponseResult {
    return FashionItemOrderDetailResponseResultFromJSONTyped(json, false);
}

export function FashionItemOrderDetailResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FashionItemOrderDetailResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FashionItemOrderDetailResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function FashionItemOrderDetailResponseResultToJSON(value?: FashionItemOrderDetailResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': FashionItemOrderDetailResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

