/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GenderType = {
    Male: 'Male',
    Female: 'Female'
} as const;
export type GenderType = typeof GenderType[keyof typeof GenderType];


export function instanceOfGenderType(value: any): boolean {
    for (const key in GenderType) {
        if (Object.prototype.hasOwnProperty.call(GenderType, key)) {
            if ((GenderType as Record<string, GenderType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GenderTypeFromJSON(json: any): GenderType {
    return GenderTypeFromJSONTyped(json, false);
}

export function GenderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenderType {
    return json as GenderType;
}

export function GenderTypeToJSON(value?: GenderType | null): any {
    return value as any;
}

