/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Refund } from './Refund';
import {
    RefundFromJSON,
    RefundFromJSONTyped,
    RefundToJSON,
} from './Refund';
import type { FashionItem } from './FashionItem';
import {
    FashionItemFromJSON,
    FashionItemFromJSONTyped,
    FashionItemToJSON,
} from './FashionItem';

/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    url?: string | null;
    /**
     * 
     * @type {FashionItem}
     * @memberof Image
     */
    fashionItem?: FashionItem;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    fashionItemId?: string;
    /**
     * 
     * @type {Refund}
     * @memberof Image
     */
    refund?: Refund;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    refundId?: string | null;
}

/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): value is Image {
    return true;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'url': json['url'] == null ? undefined : json['url'],
        'fashionItem': json['fashionItem'] == null ? undefined : FashionItemFromJSON(json['fashionItem']),
        'fashionItemId': json['fashionItemId'] == null ? undefined : json['fashionItemId'],
        'refund': json['refund'] == null ? undefined : RefundFromJSON(json['refund']),
        'refundId': json['refundId'] == null ? undefined : json['refundId'],
    };
}

export function ImageToJSON(value?: Image | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'imageId': value['imageId'],
        'url': value['url'],
        'fashionItem': FashionItemToJSON(value['fashionItem']),
        'fashionItemId': value['fashionItemId'],
        'refund': RefundToJSON(value['refund']),
        'refundId': value['refundId'],
    };
}

