/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InquiryListResponse
 */
export interface InquiryListResponse {
    /**
     * 
     * @type {string}
     * @memberof InquiryListResponse
     */
    inquiryId?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryListResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof InquiryListResponse
     */
    fullname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InquiryListResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InquiryListResponse
     */
    createdDate?: Date;
}

/**
 * Check if a given object implements the InquiryListResponse interface.
 */
export function instanceOfInquiryListResponse(value: object): value is InquiryListResponse {
    return true;
}

export function InquiryListResponseFromJSON(json: any): InquiryListResponse {
    return InquiryListResponseFromJSONTyped(json, false);
}

export function InquiryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InquiryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'inquiryId': json['inquiryId'] == null ? undefined : json['inquiryId'],
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'fullname': json['fullname'] == null ? undefined : json['fullname'],
        'message': json['message'] == null ? undefined : json['message'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
    };
}

export function InquiryListResponseToJSON(value?: InquiryListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inquiryId': value['inquiryId'],
        'shopId': value['shopId'],
        'fullname': value['fullname'],
        'message': value['message'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
    };
}

