/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InquiryListResponse } from './InquiryListResponse';
import {
    InquiryListResponseFromJSON,
    InquiryListResponseFromJSONTyped,
    InquiryListResponseToJSON,
} from './InquiryListResponse';

/**
 * 
 * @export
 * @interface InquiryListResponsePaginationResponse
 */
export interface InquiryListResponsePaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof InquiryListResponsePaginationResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof InquiryListResponsePaginationResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof InquiryListResponsePaginationResponse
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InquiryListResponsePaginationResponse
     */
    filters?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InquiryListResponsePaginationResponse
     */
    orderBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InquiryListResponsePaginationResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof InquiryListResponsePaginationResponse
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InquiryListResponsePaginationResponse
     */
    readonly hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InquiryListResponsePaginationResponse
     */
    readonly hasPrevious?: boolean;
    /**
     * 
     * @type {Array<InquiryListResponse>}
     * @memberof InquiryListResponsePaginationResponse
     */
    items?: Array<InquiryListResponse> | null;
}

/**
 * Check if a given object implements the InquiryListResponsePaginationResponse interface.
 */
export function instanceOfInquiryListResponsePaginationResponse(value: object): value is InquiryListResponsePaginationResponse {
    return true;
}

export function InquiryListResponsePaginationResponseFromJSON(json: any): InquiryListResponsePaginationResponse {
    return InquiryListResponsePaginationResponseFromJSONTyped(json, false);
}

export function InquiryListResponsePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InquiryListResponsePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(InquiryListResponseFromJSON)),
    };
}

export function InquiryListResponsePaginationResponseToJSON(value?: Omit<InquiryListResponsePaginationResponse, 'totalPages'|'hasNext'|'hasPrevious'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'searchTerm': value['searchTerm'],
        'filters': value['filters'],
        'orderBy': value['orderBy'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(InquiryListResponseToJSON)),
    };
}

