/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
} from './LoginResponse';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';

/**
 * 
 * @export
 * @interface LoginResponseResult
 */
export interface LoginResponseResult {
    /**
     * 
     * @type {LoginResponse}
     * @memberof LoginResponseResult
     */
    data?: LoginResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof LoginResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof LoginResponseResult
     */
    messages?: Array<string>;
}

/**
 * Check if a given object implements the LoginResponseResult interface.
 */
export function instanceOfLoginResponseResult(value: object): value is LoginResponseResult {
    return true;
}

export function LoginResponseResultFromJSON(json: any): LoginResponseResult {
    return LoginResponseResultFromJSONTyped(json, false);
}

export function LoginResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function LoginResponseResultToJSON(value?: LoginResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': LoginResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

