/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthRevenue } from './MonthRevenue';
import {
    MonthRevenueFromJSON,
    MonthRevenueFromJSONTyped,
    MonthRevenueToJSON,
} from './MonthRevenue';

/**
 * 
 * @export
 * @interface MonthlyRevenueDto
 */
export interface MonthlyRevenueDto {
    /**
     * 
     * @type {number}
     * @memberof MonthlyRevenueDto
     */
    year?: number;
    /**
     * 
     * @type {Array<MonthRevenue>}
     * @memberof MonthlyRevenueDto
     */
    monthlyRevenue?: Array<MonthRevenue> | null;
}

/**
 * Check if a given object implements the MonthlyRevenueDto interface.
 */
export function instanceOfMonthlyRevenueDto(value: object): value is MonthlyRevenueDto {
    return true;
}

export function MonthlyRevenueDtoFromJSON(json: any): MonthlyRevenueDto {
    return MonthlyRevenueDtoFromJSONTyped(json, false);
}

export function MonthlyRevenueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyRevenueDto {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'monthlyRevenue': json['monthlyRevenue'] == null ? undefined : ((json['monthlyRevenue'] as Array<any>).map(MonthRevenueFromJSON)),
    };
}

export function MonthlyRevenueDtoToJSON(value?: MonthlyRevenueDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'year': value['year'],
        'monthlyRevenue': value['monthlyRevenue'] == null ? undefined : ((value['monthlyRevenue'] as Array<any>).map(MonthRevenueToJSON)),
    };
}

