/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonthPayout
 */
export interface MonthPayout {
    /**
     * 
     * @type {number}
     * @memberof MonthPayout
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof MonthPayout
     */
    consignPayout?: number;
}

/**
 * Check if a given object implements the MonthPayout interface.
 */
export function instanceOfMonthPayout(value: object): value is MonthPayout {
    return true;
}

export function MonthPayoutFromJSON(json: any): MonthPayout {
    return MonthPayoutFromJSONTyped(json, false);
}

export function MonthPayoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthPayout {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'consignPayout': json['consignPayout'] == null ? undefined : json['consignPayout'],
    };
}

export function MonthPayoutToJSON(value?: MonthPayout | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'month': value['month'],
        'consignPayout': value['consignPayout'],
    };
}

