/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberDetailResponse } from './MemberDetailResponse';
import {
    MemberDetailResponseFromJSON,
    MemberDetailResponseFromJSONTyped,
    MemberDetailResponseToJSON,
} from './MemberDetailResponse';
import type { DeliveryDetailResponse } from './DeliveryDetailResponse';
import {
    DeliveryDetailResponseFromJSON,
    DeliveryDetailResponseFromJSONTyped,
    DeliveryDetailResponseToJSON,
} from './DeliveryDetailResponse';

/**
 * 
 * @export
 * @interface OrderDetailResponse
 */
export interface OrderDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof OrderDetailResponse
     */
    orderId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderDetailResponse
     */
    totalPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailResponse
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OrderDetailResponse
     */
    payementDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailResponse
     */
    memberId?: string;
    /**
     * 
     * @type {MemberDetailResponse}
     * @memberof OrderDetailResponse
     */
    member?: MemberDetailResponse;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailResponse
     */
    deliveryId?: string;
    /**
     * 
     * @type {DeliveryDetailResponse}
     * @memberof OrderDetailResponse
     */
    delivery?: DeliveryDetailResponse;
}

/**
 * Check if a given object implements the OrderDetailResponse interface.
 */
export function instanceOfOrderDetailResponse(value: object): value is OrderDetailResponse {
    return true;
}

export function OrderDetailResponseFromJSON(json: any): OrderDetailResponse {
    return OrderDetailResponseFromJSONTyped(json, false);
}

export function OrderDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'payementDate': json['payementDate'] == null ? undefined : (new Date(json['payementDate'])),
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'member': json['member'] == null ? undefined : MemberDetailResponseFromJSON(json['member']),
        'deliveryId': json['deliveryId'] == null ? undefined : json['deliveryId'],
        'delivery': json['delivery'] == null ? undefined : DeliveryDetailResponseFromJSON(json['delivery']),
    };
}

export function OrderDetailResponseToJSON(value?: OrderDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orderId': value['orderId'],
        'totalPrice': value['totalPrice'],
        'paymentMethod': value['paymentMethod'],
        'payementDate': value['payementDate'] == null ? undefined : ((value['payementDate']).toISOString()),
        'memberId': value['memberId'],
        'member': MemberDetailResponseToJSON(value['member']),
        'deliveryId': value['deliveryId'],
        'delivery': DeliveryDetailResponseToJSON(value['delivery']),
    };
}

