/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const OrderStatus = {
  AwaitingPayment: "AwaitingPayment",
  OnDelivery: "OnDelivery",
  Completed: "Completed",
  Cancelled: "Cancelled",
} as const;
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export function OrderStatusFromJSON(json: any): OrderStatus {
  return OrderStatusFromJSONTyped(json, false);
}

export function OrderStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OrderStatus {
  return json as OrderStatus;
}

export function OrderStatusToJSON(value?: OrderStatus | null): any {
  return value as any;
}
