/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderResponse } from './OrderResponse';
import {
    OrderResponseFromJSON,
    OrderResponseFromJSONTyped,
    OrderResponseToJSON,
} from './OrderResponse';

/**
 * 
 * @export
 * @interface PayOrderWithCashResponse
 */
export interface PayOrderWithCashResponse {
    /**
     * 
     * @type {string}
     * @memberof PayOrderWithCashResponse
     */
    orderId?: string;
    /**
     * 
     * @type {number}
     * @memberof PayOrderWithCashResponse
     */
    amountGiven?: number;
    /**
     * 
     * @type {OrderResponse}
     * @memberof PayOrderWithCashResponse
     */
    order?: OrderResponse;
    /**
     * 
     * @type {number}
     * @memberof PayOrderWithCashResponse
     */
    readonly change?: number;
}

/**
 * Check if a given object implements the PayOrderWithCashResponse interface.
 */
export function instanceOfPayOrderWithCashResponse(value: object): value is PayOrderWithCashResponse {
    return true;
}

export function PayOrderWithCashResponseFromJSON(json: any): PayOrderWithCashResponse {
    return PayOrderWithCashResponseFromJSONTyped(json, false);
}

export function PayOrderWithCashResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayOrderWithCashResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'amountGiven': json['amountGiven'] == null ? undefined : json['amountGiven'],
        'order': json['order'] == null ? undefined : OrderResponseFromJSON(json['order']),
        'change': json['change'] == null ? undefined : json['change'],
    };
}

export function PayOrderWithCashResponseToJSON(value?: Omit<PayOrderWithCashResponse, 'change'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orderId': value['orderId'],
        'amountGiven': value['amountGiven'],
        'order': OrderResponseToJSON(value['order']),
    };
}

