/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PointPackageStatus } from './PointPackageStatus';
import {
    PointPackageStatusFromJSON,
    PointPackageStatusFromJSONTyped,
    PointPackageStatusToJSON,
} from './PointPackageStatus';

/**
 * 
 * @export
 * @interface PointPackageDetailResponse
 */
export interface PointPackageDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof PointPackageDetailResponse
     */
    pointPackageId?: string;
    /**
     * 
     * @type {number}
     * @memberof PointPackageDetailResponse
     */
    points?: number;
    /**
     * 
     * @type {number}
     * @memberof PointPackageDetailResponse
     */
    price?: number;
    /**
     * 
     * @type {PointPackageStatus}
     * @memberof PointPackageDetailResponse
     */
    status?: PointPackageStatus;
}

/**
 * Check if a given object implements the PointPackageDetailResponse interface.
 */
export function instanceOfPointPackageDetailResponse(value: object): value is PointPackageDetailResponse {
    return true;
}

export function PointPackageDetailResponseFromJSON(json: any): PointPackageDetailResponse {
    return PointPackageDetailResponseFromJSONTyped(json, false);
}

export function PointPackageDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointPackageDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pointPackageId': json['pointPackageId'] == null ? undefined : json['pointPackageId'],
        'points': json['points'] == null ? undefined : json['points'],
        'price': json['price'] == null ? undefined : json['price'],
        'status': json['status'] == null ? undefined : PointPackageStatusFromJSON(json['status']),
    };
}

export function PointPackageDetailResponseToJSON(value?: PointPackageDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pointPackageId': value['pointPackageId'],
        'points': value['points'],
        'price': value['price'],
        'status': PointPackageStatusToJSON(value['status']),
    };
}

