/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PointPackageStatus = {
    Active: 'Active',
    Inactive: 'Inactive'
} as const;
export type PointPackageStatus = typeof PointPackageStatus[keyof typeof PointPackageStatus];


export function instanceOfPointPackageStatus(value: any): boolean {
    for (const key in PointPackageStatus) {
        if (Object.prototype.hasOwnProperty.call(PointPackageStatus, key)) {
            if ((PointPackageStatus as Record<string, PointPackageStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PointPackageStatusFromJSON(json: any): PointPackageStatus {
    return PointPackageStatusFromJSONTyped(json, false);
}

export function PointPackageStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointPackageStatus {
    return json as PointPackageStatus;
}

export function PointPackageStatusToJSON(value?: PointPackageStatus | null): any {
    return value as any;
}

