/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PointPackageListResponse } from './PointPackageListResponse';
import {
    PointPackageListResponseFromJSON,
    PointPackageListResponseFromJSONTyped,
    PointPackageListResponseToJSON,
} from './PointPackageListResponse';

/**
 * 
 * @export
 * @interface PointPackageListResponsePaginationResponse
 */
export interface PointPackageListResponsePaginationResponse {
    /**
     * 
     * @type {number}
     * @memberof PointPackageListResponsePaginationResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PointPackageListResponsePaginationResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof PointPackageListResponsePaginationResponse
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PointPackageListResponsePaginationResponse
     */
    filters?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof PointPackageListResponsePaginationResponse
     */
    orderBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PointPackageListResponsePaginationResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PointPackageListResponsePaginationResponse
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PointPackageListResponsePaginationResponse
     */
    readonly hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PointPackageListResponsePaginationResponse
     */
    readonly hasPrevious?: boolean;
    /**
     * 
     * @type {Array<PointPackageListResponse>}
     * @memberof PointPackageListResponsePaginationResponse
     */
    items?: Array<PointPackageListResponse> | null;
}

/**
 * Check if a given object implements the PointPackageListResponsePaginationResponse interface.
 */
export function instanceOfPointPackageListResponsePaginationResponse(value: object): value is PointPackageListResponsePaginationResponse {
    return true;
}

export function PointPackageListResponsePaginationResponseFromJSON(json: any): PointPackageListResponsePaginationResponse {
    return PointPackageListResponsePaginationResponseFromJSONTyped(json, false);
}

export function PointPackageListResponsePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointPackageListResponsePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(PointPackageListResponseFromJSON)),
    };
}

export function PointPackageListResponsePaginationResponseToJSON(value?: Omit<PointPackageListResponsePaginationResponse, 'totalPages'|'hasNext'|'hasPrevious'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'searchTerm': value['searchTerm'],
        'filters': value['filters'],
        'orderBy': value['orderBy'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(PointPackageListResponseToJSON)),
    };
}

