/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PurchaseOrderRequest
 */
export interface PurchaseOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderRequest
     */
    memberId?: string;
}

/**
 * Check if a given object implements the PurchaseOrderRequest interface.
 */
export function instanceOfPurchaseOrderRequest(value: object): value is PurchaseOrderRequest {
    return true;
}

export function PurchaseOrderRequestFromJSON(json: any): PurchaseOrderRequest {
    return PurchaseOrderRequestFromJSONTyped(json, false);
}

export function PurchaseOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
    };
}

export function PurchaseOrderRequestToJSON(value?: PurchaseOrderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberId': value['memberId'],
    };
}

