/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { RefundResponsePaginationResponse } from './RefundResponsePaginationResponse';
import {
    RefundResponsePaginationResponseFromJSON,
    RefundResponsePaginationResponseFromJSONTyped,
    RefundResponsePaginationResponseToJSON,
} from './RefundResponsePaginationResponse';

/**
 * 
 * @export
 * @interface RefundResponsePaginationResponseResult
 */
export interface RefundResponsePaginationResponseResult {
    /**
     * 
     * @type {RefundResponsePaginationResponse}
     * @memberof RefundResponsePaginationResponseResult
     */
    data?: RefundResponsePaginationResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof RefundResponsePaginationResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof RefundResponsePaginationResponseResult
     */
    messages?: Array<string> | null;
}

/**
 * Check if a given object implements the RefundResponsePaginationResponseResult interface.
 */
export function instanceOfRefundResponsePaginationResponseResult(value: object): value is RefundResponsePaginationResponseResult {
    return true;
}

export function RefundResponsePaginationResponseResultFromJSON(json: any): RefundResponsePaginationResponseResult {
    return RefundResponsePaginationResponseResultFromJSONTyped(json, false);
}

export function RefundResponsePaginationResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundResponsePaginationResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : RefundResponsePaginationResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function RefundResponsePaginationResponseResultToJSON(value?: RefundResponsePaginationResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': RefundResponsePaginationResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

