/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Auction } from './Auction';
import {
    AuctionFromJSON,
    AuctionFromJSONTyped,
    AuctionToJSON,
} from './Auction';
import type { Timeslot } from './Timeslot';
import {
    TimeslotFromJSON,
    TimeslotFromJSONTyped,
    TimeslotToJSON,
} from './Timeslot';

/**
 * 
 * @export
 * @interface Schedule
 */
export interface Schedule {
    /**
     * 
     * @type {string}
     * @memberof Schedule
     */
    scheduleId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Schedule
     */
    date?: Date;
    /**
     * 
     * @type {Timeslot}
     * @memberof Schedule
     */
    timeslot?: Timeslot;
    /**
     * 
     * @type {string}
     * @memberof Schedule
     */
    timeslotId?: string;
    /**
     * 
     * @type {Auction}
     * @memberof Schedule
     */
    auction?: Auction;
    /**
     * 
     * @type {string}
     * @memberof Schedule
     */
    auctionId?: string;
}

/**
 * Check if a given object implements the Schedule interface.
 */
export function instanceOfSchedule(value: object): value is Schedule {
    return true;
}

export function ScheduleFromJSON(json: any): Schedule {
    return ScheduleFromJSONTyped(json, false);
}

export function ScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Schedule {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleId': json['scheduleId'] == null ? undefined : json['scheduleId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'timeslot': json['timeslot'] == null ? undefined : TimeslotFromJSON(json['timeslot']),
        'timeslotId': json['timeslotId'] == null ? undefined : json['timeslotId'],
        'auction': json['auction'] == null ? undefined : AuctionFromJSON(json['auction']),
        'auctionId': json['auctionId'] == null ? undefined : json['auctionId'],
    };
}

export function ScheduleToJSON(value?: Schedule | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scheduleId': value['scheduleId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'timeslot': TimeslotToJSON(value['timeslot']),
        'timeslotId': value['timeslotId'],
        'auction': AuctionToJSON(value['auction']),
        'auctionId': value['auctionId'],
    };
}

