/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FashionItemDetailResponseOrderDetailResponse } from './FashionItemDetailResponseOrderDetailResponse';
import {
    FashionItemDetailResponseOrderDetailResponseFromJSON,
    FashionItemDetailResponseOrderDetailResponseFromJSONTyped,
    FashionItemDetailResponseOrderDetailResponseToJSON,
} from './FashionItemDetailResponseOrderDetailResponse';

/**
 * 
 * @export
 * @interface ShopOrderResponse
 */
export interface ShopOrderResponse {
    /**
     * 
     * @type {string}
     * @memberof ShopOrderResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopOrderResponse
     */
    shopAddress?: string | null;
    /**
     * 
     * @type {Array<FashionItemDetailResponseOrderDetailResponse>}
     * @memberof ShopOrderResponse
     */
    items?: Array<FashionItemDetailResponseOrderDetailResponse> | null;
}

/**
 * Check if a given object implements the ShopOrderResponse interface.
 */
export function instanceOfShopOrderResponse(value: object): value is ShopOrderResponse {
    return true;
}

export function ShopOrderResponseFromJSON(json: any): ShopOrderResponse {
    return ShopOrderResponseFromJSONTyped(json, false);
}

export function ShopOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'shopAddress': json['shopAddress'] == null ? undefined : json['shopAddress'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FashionItemDetailResponseOrderDetailResponseFromJSON)),
    };
}

export function ShopOrderResponseToJSON(value?: ShopOrderResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'shopId': value['shopId'],
        'shopAddress': value['shopAddress'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FashionItemDetailResponseOrderDetailResponseToJSON)),
    };
}

