/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShopDetailResponse
 */
export interface ShopDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof ShopDetailResponse
     */
    shopId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopDetailResponse
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopDetailResponse
     */
    staffId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopDetailResponse
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the ShopDetailResponse interface.
 */
export function instanceOfShopDetailResponse(value: object): value is ShopDetailResponse {
    return true;
}

export function ShopDetailResponseFromJSON(json: any): ShopDetailResponse {
    return ShopDetailResponseFromJSONTyped(json, false);
}

export function ShopDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
        'address': json['address'] == null ? undefined : json['address'],
        'staffId': json['staffId'] == null ? undefined : json['staffId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function ShopDetailResponseToJSON(value?: ShopDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'shopId': value['shopId'],
        'address': value['address'],
        'staffId': value['staffId'],
        'phone': value['phone'],
    };
}

