/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountStatus } from './AccountStatus';
import {
    AccountStatusFromJSON,
    AccountStatusFromJSONTyped,
    AccountStatusToJSON,
} from './AccountStatus';
import type { Shop } from './Shop';
import {
    ShopFromJSON,
    ShopFromJSONTyped,
    ShopToJSON,
} from './Shop';
import type { Roles } from './Roles';
import {
    RolesFromJSON,
    RolesFromJSONTyped,
    RolesToJSON,
} from './Roles';

/**
 * 
 * @export
 * @interface Staff
 */
export interface Staff {
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    passwordSalt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    fullname?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Staff
     */
    verifiedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    passwordResetToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Staff
     */
    resetTokenExpires?: Date | null;
    /**
     * 
     * @type {Roles}
     * @memberof Staff
     */
    role?: Roles;
    /**
     * 
     * @type {AccountStatus}
     * @memberof Staff
     */
    status?: AccountStatus;
    /**
     * 
     * @type {number}
     * @memberof Staff
     */
    balance?: number;
    /**
     * 
     * @type {Shop}
     * @memberof Staff
     */
    shop?: Shop;
}

/**
 * Check if a given object implements the Staff interface.
 */
export function instanceOfStaff(value: object): value is Staff {
    return true;
}

export function StaffFromJSON(json: any): Staff {
    return StaffFromJSONTyped(json, false);
}

export function StaffFromJSONTyped(json: any, ignoreDiscriminator: boolean): Staff {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'passwordSalt': json['passwordSalt'] == null ? undefined : json['passwordSalt'],
        'fullname': json['fullname'] == null ? undefined : json['fullname'],
        'verifiedAt': json['verifiedAt'] == null ? undefined : (new Date(json['verifiedAt'])),
        'passwordResetToken': json['passwordResetToken'] == null ? undefined : json['passwordResetToken'],
        'resetTokenExpires': json['resetTokenExpires'] == null ? undefined : (new Date(json['resetTokenExpires'])),
        'role': json['role'] == null ? undefined : RolesFromJSON(json['role']),
        'status': json['status'] == null ? undefined : AccountStatusFromJSON(json['status']),
        'balance': json['balance'] == null ? undefined : json['balance'],
        'shop': json['shop'] == null ? undefined : ShopFromJSON(json['shop']),
    };
}

export function StaffToJSON(value?: Staff | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'email': value['email'],
        'phone': value['phone'],
        'passwordHash': value['passwordHash'],
        'passwordSalt': value['passwordSalt'],
        'fullname': value['fullname'],
        'verifiedAt': value['verifiedAt'] == null ? undefined : ((value['verifiedAt'] as any).toISOString()),
        'passwordResetToken': value['passwordResetToken'],
        'resetTokenExpires': value['resetTokenExpires'] == null ? undefined : ((value['resetTokenExpires'] as any).toISOString()),
        'role': RolesToJSON(value['role']),
        'status': AccountStatusToJSON(value['status']),
        'balance': value['balance'],
        'shop': ShopToJSON(value['shop']),
    };
}

