/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffDetailResponse
 */
export interface StaffDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof StaffDetailResponse
     */
    staffId?: string;
    /**
     * 
     * @type {string}
     * @memberof StaffDetailResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof StaffDetailResponse
     */
    phone?: string;
}

/**
 * Check if a given object implements the StaffDetailResponse interface.
 */
export function instanceOfStaffDetailResponse(value: object): value is StaffDetailResponse {
    return true;
}

export function StaffDetailResponseFromJSON(json: any): StaffDetailResponse {
    return StaffDetailResponseFromJSONTyped(json, false);
}

export function StaffDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'staffId': json['staffId'] == null ? undefined : json['staffId'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function StaffDetailResponseToJSON(value?: StaffDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'staffId': value['staffId'],
        'name': value['name'],
        'phone': value['phone'],
    };
}

