/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionRequest
 */
export interface TransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionRequest
     */
    page?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionRequest
     */
    pageSize?: number | null;
}

/**
 * Check if a given object implements the TransactionRequest interface.
 */
export function instanceOfTransactionRequest(value: object): value is TransactionRequest {
    return true;
}

export function TransactionRequestFromJSON(json: any): TransactionRequest {
    return TransactionRequestFromJSONTyped(json, false);
}

export function TransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function TransactionRequestToJSON(value?: TransactionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

