/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWalletRequest
 */
export interface UpdateWalletRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWalletRequest
     */
    bankAccountNumber: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWalletRequest
     */
    bankName: string;
}

/**
 * Check if a given object implements the UpdateWalletRequest interface.
 */
export function instanceOfUpdateWalletRequest(value: object): value is UpdateWalletRequest {
    if (!('bankAccountNumber' in value) || value['bankAccountNumber'] === undefined) return false;
    if (!('bankName' in value) || value['bankName'] === undefined) return false;
    return true;
}

export function UpdateWalletRequestFromJSON(json: any): UpdateWalletRequest {
    return UpdateWalletRequestFromJSONTyped(json, false);
}

export function UpdateWalletRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWalletRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bankAccountNumber': json['bankAccountNumber'],
        'bankName': json['bankName'],
    };
}

export function UpdateWalletRequestToJSON(value?: UpdateWalletRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bankAccountNumber': value['bankAccountNumber'],
        'bankName': value['bankName'],
    };
}

