/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberDetailResponse } from './MemberDetailResponse';
import {
    MemberDetailResponseFromJSON,
    MemberDetailResponseFromJSONTyped,
    MemberDetailResponseToJSON,
} from './MemberDetailResponse';

/**
 * 
 * @export
 * @interface WalletDetailResponse
 */
export interface WalletDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof WalletDetailResponse
     */
    walletId?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletDetailResponse
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletDetailResponse
     */
    memberId?: string;
    /**
     * 
     * @type {MemberDetailResponse}
     * @memberof WalletDetailResponse
     */
    member?: MemberDetailResponse;
    /**
     * 
     * @type {string}
     * @memberof WalletDetailResponse
     */
    bankAccountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletDetailResponse
     */
    bankName?: string | null;
}

/**
 * Check if a given object implements the WalletDetailResponse interface.
 */
export function instanceOfWalletDetailResponse(value: object): value is WalletDetailResponse {
    return true;
}

export function WalletDetailResponseFromJSON(json: any): WalletDetailResponse {
    return WalletDetailResponseFromJSONTyped(json, false);
}

export function WalletDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'walletId': json['walletId'] == null ? undefined : json['walletId'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'member': json['member'] == null ? undefined : MemberDetailResponseFromJSON(json['member']),
        'bankAccountNumber': json['bankAccountNumber'] == null ? undefined : json['bankAccountNumber'],
        'bankName': json['bankName'] == null ? undefined : json['bankName'],
    };
}

export function WalletDetailResponseToJSON(value?: WalletDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'walletId': value['walletId'],
        'balance': value['balance'],
        'memberId': value['memberId'],
        'member': MemberDetailResponseToJSON(value['member']),
        'bankAccountNumber': value['bankAccountNumber'],
        'bankName': value['bankName'],
    };
}

