/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultStatus } from './ResultStatus';
import {
    ResultStatusFromJSON,
    ResultStatusFromJSONTyped,
    ResultStatusToJSON,
} from './ResultStatus';
import type { WalletResponse } from './WalletResponse';
import {
    WalletResponseFromJSON,
    WalletResponseFromJSONTyped,
    WalletResponseToJSON,
} from './WalletResponse';

/**
 * 
 * @export
 * @interface WalletResponseResult
 */
export interface WalletResponseResult {
    /**
     * 
     * @type {WalletResponse}
     * @memberof WalletResponseResult
     */
    data?: WalletResponse;
    /**
     * 
     * @type {ResultStatus}
     * @memberof WalletResponseResult
     */
    resultStatus?: ResultStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof WalletResponseResult
     */
    messages?: Array<string>;
}

/**
 * Check if a given object implements the WalletResponseResult interface.
 */
export function instanceOfWalletResponseResult(value: object): value is WalletResponseResult {
    return true;
}

export function WalletResponseResultFromJSON(json: any): WalletResponseResult {
    return WalletResponseResultFromJSONTyped(json, false);
}

export function WalletResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : WalletResponseFromJSON(json['data']),
        'resultStatus': json['resultStatus'] == null ? undefined : ResultStatusFromJSON(json['resultStatus']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function WalletResponseResultToJSON(value?: WalletResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': WalletResponseToJSON(value['data']),
        'resultStatus': ResultStatusToJSON(value['resultStatus']),
        'messages': value['messages'],
    };
}

