/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletResponse
 */
export interface WalletResponse {
    /**
     * 
     * @type {number}
     * @memberof WalletResponse
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletResponse
     */
    bankAccountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletResponse
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletResponse
     */
    accountName?: string;
}

/**
 * Check if a given object implements the WalletResponse interface.
 */
export function instanceOfWalletResponse(value: object): value is WalletResponse {
    return true;
}

export function WalletResponseFromJSON(json: any): WalletResponse {
    return WalletResponseFromJSONTyped(json, false);
}

export function WalletResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : json['balance'],
        'bankAccountNumber': json['bankAccountNumber'] == null ? undefined : json['bankAccountNumber'],
        'bankName': json['bankName'] == null ? undefined : json['bankName'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
    };
}

export function WalletResponseToJSON(value?: WalletResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'balance': value['balance'],
        'bankAccountNumber': value['bankAccountNumber'],
        'bankName': value['bankName'],
        'accountName': value['accountName'],
    };
}

