/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuctionDepositDetailResponse,
  AuctionDepositListResponsePaginationResponse,
  AuctionDetailResponse,
  AuctionListResponsePaginationResponse,
  BidDetailResponse,
  BidListResponsePaginationResponse,
  CreateAuctionDepositRequest,
  CreateAuctionRequest,
  CreateBidRequest,
  HasMemberPlacedDepositResult,
  ProblemDetails,
  UpdateAuctionRequest,
  UpdateBidRequest,
} from '../models/index';
import {
    AuctionDepositDetailResponseFromJSON,
    AuctionDepositDetailResponseToJSON,
    AuctionDepositListResponsePaginationResponseFromJSON,
    AuctionDepositListResponsePaginationResponseToJSON,
    AuctionDetailResponseFromJSON,
    AuctionDetailResponseToJSON,
    AuctionListResponsePaginationResponseFromJSON,
    AuctionListResponsePaginationResponseToJSON,
    BidDetailResponseFromJSON,
    BidDetailResponseToJSON,
    BidListResponsePaginationResponseFromJSON,
    BidListResponsePaginationResponseToJSON,
    CreateAuctionDepositRequestFromJSON,
    CreateAuctionDepositRequestToJSON,
    CreateAuctionRequestFromJSON,
    CreateAuctionRequestToJSON,
    CreateBidRequestFromJSON,
    CreateBidRequestToJSON,
    HasMemberPlacedDepositResultFromJSON,
    HasMemberPlacedDepositResultToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    UpdateAuctionRequestFromJSON,
    UpdateAuctionRequestToJSON,
    UpdateBidRequestFromJSON,
    UpdateBidRequestToJSON,
} from '../models/index';

export interface ApiAuctionsAuctionIdDepositsDepositIdDeleteRequest {
    auctionId: string;
    depositId: string;
}

export interface ApiAuctionsAuctionIdDepositsDepositIdGetRequest {
    auctionId: string;
    depositId: string;
}

export interface ApiAuctionsAuctionIdDepositsDepositIdPutRequest {
    auctionId: string;
    depositId: string;
    body?: object;
}

export interface ApiAuctionsAuctionIdDepositsGetRequest {
    auctionId: string;
    page?: number;
    pageSize?: number;
}

export interface ApiAuctionsAuctionIdDepositsHasDepositGetRequest {
    auctionId: string;
    memberId?: string;
}

export interface ApiAuctionsAuctionIdDepositsPlaceDepositPostRequest {
    auctionId: string;
    createAuctionDepositRequest?: CreateAuctionDepositRequest;
}

export interface ApiAuctionsGetRequest {
    searchTerm?: string;
    pageNumber?: number;
    pageSize?: number;
}

export interface ApiAuctionsIdApprovePutRequest {
    id: string;
}

export interface ApiAuctionsIdBidsBidIdDeleteRequest {
    id: string;
    bidId: string;
}

export interface ApiAuctionsIdBidsBidIdGetRequest {
    id: string;
    bidId: string;
}

export interface ApiAuctionsIdBidsBidIdPutRequest {
    id: string;
    bidId: string;
    updateBidRequest?: UpdateBidRequest;
}

export interface ApiAuctionsIdBidsGetRequest {
    id: string;
    pageNumber?: number;
    pageSize?: number;
}

export interface ApiAuctionsIdBidsLatestGetRequest {
    id: string;
}

export interface ApiAuctionsIdBidsPlaceBidPostRequest {
    id: string;
    createBidRequest?: CreateBidRequest;
}

export interface ApiAuctionsIdDeleteRequest {
    id: string;
}

export interface ApiAuctionsIdGetRequest {
    id: string;
}

export interface ApiAuctionsIdPutRequest {
    id: string;
    updateAuctionRequest?: UpdateAuctionRequest;
}

export interface ApiAuctionsIdRejectPutRequest {
    id: string;
}

export interface ApiAuctionsPostRequest {
    createAuctionRequest?: CreateAuctionRequest;
}

/**
 * 
 */
export class AuctionApi extends runtime.BaseAPI {

    /**
     */
    async apiAuctionsAuctionIdDepositsDepositIdDeleteRaw(requestParameters: ApiAuctionsAuctionIdDepositsDepositIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['auctionId'] == null) {
            throw new runtime.RequiredError(
                'auctionId',
                'Required parameter "auctionId" was null or undefined when calling apiAuctionsAuctionIdDepositsDepositIdDelete().'
            );
        }

        if (requestParameters['depositId'] == null) {
            throw new runtime.RequiredError(
                'depositId',
                'Required parameter "depositId" was null or undefined when calling apiAuctionsAuctionIdDepositsDepositIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{auctionId}/deposits/{depositId}`.replace(`{${"auctionId"}}`, encodeURIComponent(String(requestParameters['auctionId']))).replace(`{${"depositId"}}`, encodeURIComponent(String(requestParameters['depositId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsDepositIdDelete(requestParameters: ApiAuctionsAuctionIdDepositsDepositIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuctionsAuctionIdDepositsDepositIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsDepositIdGetRaw(requestParameters: ApiAuctionsAuctionIdDepositsDepositIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDepositDetailResponse>> {
        if (requestParameters['auctionId'] == null) {
            throw new runtime.RequiredError(
                'auctionId',
                'Required parameter "auctionId" was null or undefined when calling apiAuctionsAuctionIdDepositsDepositIdGet().'
            );
        }

        if (requestParameters['depositId'] == null) {
            throw new runtime.RequiredError(
                'depositId',
                'Required parameter "depositId" was null or undefined when calling apiAuctionsAuctionIdDepositsDepositIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{auctionId}/deposits/{depositId}`.replace(`{${"auctionId"}}`, encodeURIComponent(String(requestParameters['auctionId']))).replace(`{${"depositId"}}`, encodeURIComponent(String(requestParameters['depositId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDepositDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsDepositIdGet(requestParameters: ApiAuctionsAuctionIdDepositsDepositIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDepositDetailResponse> {
        const response = await this.apiAuctionsAuctionIdDepositsDepositIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsDepositIdPutRaw(requestParameters: ApiAuctionsAuctionIdDepositsDepositIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDepositDetailResponse>> {
        if (requestParameters['auctionId'] == null) {
            throw new runtime.RequiredError(
                'auctionId',
                'Required parameter "auctionId" was null or undefined when calling apiAuctionsAuctionIdDepositsDepositIdPut().'
            );
        }

        if (requestParameters['depositId'] == null) {
            throw new runtime.RequiredError(
                'depositId',
                'Required parameter "depositId" was null or undefined when calling apiAuctionsAuctionIdDepositsDepositIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{auctionId}/deposits/{depositId}`.replace(`{${"auctionId"}}`, encodeURIComponent(String(requestParameters['auctionId']))).replace(`{${"depositId"}}`, encodeURIComponent(String(requestParameters['depositId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDepositDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsDepositIdPut(requestParameters: ApiAuctionsAuctionIdDepositsDepositIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDepositDetailResponse> {
        const response = await this.apiAuctionsAuctionIdDepositsDepositIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsGetRaw(requestParameters: ApiAuctionsAuctionIdDepositsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDepositListResponsePaginationResponse>> {
        if (requestParameters['auctionId'] == null) {
            throw new runtime.RequiredError(
                'auctionId',
                'Required parameter "auctionId" was null or undefined when calling apiAuctionsAuctionIdDepositsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{auctionId}/deposits`.replace(`{${"auctionId"}}`, encodeURIComponent(String(requestParameters['auctionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDepositListResponsePaginationResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsGet(requestParameters: ApiAuctionsAuctionIdDepositsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDepositListResponsePaginationResponse> {
        const response = await this.apiAuctionsAuctionIdDepositsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsHasDepositGetRaw(requestParameters: ApiAuctionsAuctionIdDepositsHasDepositGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HasMemberPlacedDepositResult>> {
        if (requestParameters['auctionId'] == null) {
            throw new runtime.RequiredError(
                'auctionId',
                'Required parameter "auctionId" was null or undefined when calling apiAuctionsAuctionIdDepositsHasDepositGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['memberId'] != null) {
            queryParameters['MemberId'] = requestParameters['memberId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{auctionId}/deposits/has-deposit`.replace(`{${"auctionId"}}`, encodeURIComponent(String(requestParameters['auctionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HasMemberPlacedDepositResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsHasDepositGet(requestParameters: ApiAuctionsAuctionIdDepositsHasDepositGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HasMemberPlacedDepositResult> {
        const response = await this.apiAuctionsAuctionIdDepositsHasDepositGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsPlaceDepositPostRaw(requestParameters: ApiAuctionsAuctionIdDepositsPlaceDepositPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDepositDetailResponse>> {
        if (requestParameters['auctionId'] == null) {
            throw new runtime.RequiredError(
                'auctionId',
                'Required parameter "auctionId" was null or undefined when calling apiAuctionsAuctionIdDepositsPlaceDepositPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{auctionId}/deposits/place_deposit`.replace(`{${"auctionId"}}`, encodeURIComponent(String(requestParameters['auctionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAuctionDepositRequestToJSON(requestParameters['createAuctionDepositRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDepositDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsAuctionIdDepositsPlaceDepositPost(requestParameters: ApiAuctionsAuctionIdDepositsPlaceDepositPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDepositDetailResponse> {
        const response = await this.apiAuctionsAuctionIdDepositsPlaceDepositPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsCurrentTimeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/current-time`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuctionsCurrentTimeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuctionsCurrentTimeGetRaw(initOverrides);
    }

    /**
     */
    async apiAuctionsGetRaw(requestParameters: ApiAuctionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionListResponsePaginationResponse>> {
        const queryParameters: any = {};

        if (requestParameters['searchTerm'] != null) {
            queryParameters['SearchTerm'] = requestParameters['searchTerm'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionListResponsePaginationResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsGet(requestParameters: ApiAuctionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionListResponsePaginationResponse> {
        const response = await this.apiAuctionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdApprovePutRaw(requestParameters: ApiAuctionsIdApprovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdApprovePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/approve`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdApprovePut(requestParameters: ApiAuctionsIdApprovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDetailResponse> {
        const response = await this.apiAuctionsIdApprovePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdBidsBidIdDeleteRaw(requestParameters: ApiAuctionsIdBidsBidIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdBidsBidIdDelete().'
            );
        }

        if (requestParameters['bidId'] == null) {
            throw new runtime.RequiredError(
                'bidId',
                'Required parameter "bidId" was null or undefined when calling apiAuctionsIdBidsBidIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/bids/{bidId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"bidId"}}`, encodeURIComponent(String(requestParameters['bidId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuctionsIdBidsBidIdDelete(requestParameters: ApiAuctionsIdBidsBidIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuctionsIdBidsBidIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuctionsIdBidsBidIdGetRaw(requestParameters: ApiAuctionsIdBidsBidIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BidDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdBidsBidIdGet().'
            );
        }

        if (requestParameters['bidId'] == null) {
            throw new runtime.RequiredError(
                'bidId',
                'Required parameter "bidId" was null or undefined when calling apiAuctionsIdBidsBidIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/bids/{bidId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"bidId"}}`, encodeURIComponent(String(requestParameters['bidId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BidDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdBidsBidIdGet(requestParameters: ApiAuctionsIdBidsBidIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BidDetailResponse> {
        const response = await this.apiAuctionsIdBidsBidIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdBidsBidIdPutRaw(requestParameters: ApiAuctionsIdBidsBidIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BidDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdBidsBidIdPut().'
            );
        }

        if (requestParameters['bidId'] == null) {
            throw new runtime.RequiredError(
                'bidId',
                'Required parameter "bidId" was null or undefined when calling apiAuctionsIdBidsBidIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/bids/{bidId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"bidId"}}`, encodeURIComponent(String(requestParameters['bidId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateBidRequestToJSON(requestParameters['updateBidRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BidDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdBidsBidIdPut(requestParameters: ApiAuctionsIdBidsBidIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BidDetailResponse> {
        const response = await this.apiAuctionsIdBidsBidIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdBidsGetRaw(requestParameters: ApiAuctionsIdBidsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BidListResponsePaginationResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdBidsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/bids`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BidListResponsePaginationResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdBidsGet(requestParameters: ApiAuctionsIdBidsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BidListResponsePaginationResponse> {
        const response = await this.apiAuctionsIdBidsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdBidsLatestGetRaw(requestParameters: ApiAuctionsIdBidsLatestGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BidDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdBidsLatestGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/bids/latest`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BidDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdBidsLatestGet(requestParameters: ApiAuctionsIdBidsLatestGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BidDetailResponse> {
        const response = await this.apiAuctionsIdBidsLatestGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdBidsPlaceBidPostRaw(requestParameters: ApiAuctionsIdBidsPlaceBidPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BidDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdBidsPlaceBidPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/bids/place_bid`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBidRequestToJSON(requestParameters['createBidRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BidDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdBidsPlaceBidPost(requestParameters: ApiAuctionsIdBidsPlaceBidPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BidDetailResponse> {
        const response = await this.apiAuctionsIdBidsPlaceBidPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdDeleteRaw(requestParameters: ApiAuctionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuctionsIdDelete(requestParameters: ApiAuctionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuctionsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuctionsIdGetRaw(requestParameters: ApiAuctionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdGet(requestParameters: ApiAuctionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDetailResponse> {
        const response = await this.apiAuctionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdPutRaw(requestParameters: ApiAuctionsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAuctionRequestToJSON(requestParameters['updateAuctionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdPut(requestParameters: ApiAuctionsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDetailResponse> {
        const response = await this.apiAuctionsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsIdRejectPutRaw(requestParameters: ApiAuctionsIdRejectPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAuctionsIdRejectPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions/{id}/reject`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsIdRejectPut(requestParameters: ApiAuctionsIdRejectPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDetailResponse> {
        const response = await this.apiAuctionsIdRejectPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuctionsPostRaw(requestParameters: ApiAuctionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuctionDetailResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auctions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAuctionRequestToJSON(requestParameters['createAuctionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuctionDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuctionsPost(requestParameters: ApiAuctionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuctionDetailResponse> {
        const response = await this.apiAuctionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
