/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FashionItemDetailResponsePaginationResponseResult,
} from '../models/index';
import {
    FashionItemDetailResponsePaginationResponseResultFromJSON,
    FashionItemDetailResponsePaginationResponseResultToJSON,
} from '../models/index';

export interface ApiFashionitemsGetRequest {
    searchTerm?: string;
    pageNumber?: number;
    pageSize?: number;
}

/**
 * 
 */
export class FashionItemApi extends runtime.BaseAPI {

    /**
     */
    async apiFashionitemsGetRaw(requestParameters: ApiFashionitemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FashionItemDetailResponsePaginationResponseResult>> {
        const queryParameters: any = {};

        if (requestParameters['searchTerm'] != null) {
            queryParameters['SearchTerm'] = requestParameters['searchTerm'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/fashionitems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FashionItemDetailResponsePaginationResponseResultFromJSON(jsonValue));
    }

    /**
     */
    async apiFashionitemsGet(requestParameters: ApiFashionitemsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FashionItemDetailResponsePaginationResponseResult> {
        const response = await this.apiFashionitemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
