/* tslint:disable */
/* eslint-disable */
/**
 * Give Away API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApproveWithdrawResponse,
} from '../models/index';
import {
    ApproveWithdrawResponseFromJSON,
    ApproveWithdrawResponseToJSON,
} from '../models/index';

export interface ApiWithdrawsWithdrawIdApprovePutRequest {
    withdrawId: string;
}

/**
 * 
 */
export class WithdrawApi extends runtime.BaseAPI {

    /**
     */
    async apiWithdrawsWithdrawIdApprovePutRaw(requestParameters: ApiWithdrawsWithdrawIdApprovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApproveWithdrawResponse>> {
        if (requestParameters['withdrawId'] == null) {
            throw new runtime.RequiredError(
                'withdrawId',
                'Required parameter "withdrawId" was null or undefined when calling apiWithdrawsWithdrawIdApprovePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/withdraws/{withdrawId}/approve`.replace(`{${"withdrawId"}}`, encodeURIComponent(String(requestParameters['withdrawId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApproveWithdrawResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiWithdrawsWithdrawIdApprovePut(requestParameters: ApiWithdrawsWithdrawIdApprovePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApproveWithdrawResponse> {
        const response = await this.apiWithdrawsWithdrawIdApprovePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
