let newData = {
  pageNumber: 1,
  pageSize: 5,
  searchTerm: "",
  filters: [],
  orderBy: "name",
  totalCount: 20,
  totalPages: 4,
  hasNext: true,
  hasPrevious: false,
  items: [
    {
      itemId: "item-1",
      type: "For Auction",
      sellingPrice: 60,
      name: "Vintage Hat",
      description: "Slightly used but in good shape.",
      quantity: 2,
      value: "71%",
      condition: "Used",
      consignDuration: 21,
      status: "Available",
      shopAddress: "1 Hat St, Hatville",
      startDate: "2024-01-01T00:00:00.000Z",
      endDate: "2024-02-01T00:00:00.000Z",
      consigner: "Alice Smith",
      categoryName: "Accessories",
    },
    {
      itemId: "item-2",
      type: "For Sale",
      sellingPrice: 70,
      name: "Vintage Jacket",
      description: "In perfect condition, brand new.",
      quantity: 1,
      value: "72%",
      condition: "New",
      consignDuration: 22,
      status: "Available",
      shopAddress: "2 Jacket St, Jackettown",
      startDate: "2024-01-02T00:00:00.000Z",
      endDate: "2024-02-02T00:00:00.000Z",
      consigner: "Bob Johnson",
      categoryName: "Clothing",
    },
    {
      itemId: "item-3",
      type: "For Auction",
      sellingPrice: 80,
      name: "Leather Boots",
      description: "Minor signs of wear, very stylish.",
      quantity: 3,
      value: "73%",
      condition: "Used",
      consignDuration: 23,
      status: "Available",
      shopAddress: "3 Boot Rd, Bootville",
      startDate: "2024-01-03T00:00:00.000Z",
      endDate: "2024-02-03T00:00:00.000Z",
      consigner: "Charlie Brown",
      categoryName: "Footwear",
    },
    {
      itemId: "item-4",
      type: "For Sale",
      sellingPrice: 90,
      name: "Silk Scarf",
      description: "Beautiful and elegant.",
      quantity: 2,
      value: "74%",
      condition: "New",
      consignDuration: 24,
      status: "Available",
      shopAddress: "4 Scarf St, Scarf City",
      startDate: "2024-01-04T00:00:00.000Z",
      endDate: "2024-02-04T00:00:00.000Z",
      consigner: "Diana Prince",
      categoryName: "Accessories",
    },
    {
      itemId: "item-5",
      type: "For Auction",
      sellingPrice: 100,
      name: "Vintage Sunglasses",
      description: "Retro style, very fashionable.",
      quantity: 1,
      value: "75%",
      condition: "Used",
      consignDuration: 25,
      status: "Available",
      shopAddress: "5 Shades Ave, Sunglass Town",
      startDate: "2024-01-05T00:00:00.000Z",
      endDate: "2024-02-05T00:00:00.000Z",
      consigner: "Eve Adams",
      categoryName: "Accessories",
    },
    {
      itemId: "item-6",
      type: "For Sale",
      sellingPrice: 110,
      name: "Vintage Necklace",
      description: "Beautiful piece, looks new.",
      quantity: 2,
      value: "76%",
      condition: "New",
      consignDuration: 26,
      status: "Available",
      shopAddress: "6 Jewel Ln, Necklace City",
      startDate: "2024-01-06T00:00:00.000Z",
      endDate: "2024-02-06T00:00:00.000Z",
      consigner: "Frank Miller",
      categoryName: "Jewelry",
    },
    {
      itemId: "item-7",
      type: "For Auction",
      sellingPrice: 120,
      name: "Designer Handbag",
      description: "Gently used, excellent condition.",
      quantity: 3,
      value: "77%",
      condition: "Used",
      consignDuration: 27,
      status: "Available",
      shopAddress: "7 Bag Blvd, Handbag City",
      startDate: "2024-01-07T00:00:00.000Z",
      endDate: "2024-02-07T00:00:00.000Z",
      consigner: "Gina Lopez",
      categoryName: "Bags",
    },
    {
      itemId: "item-8",
      type: "For Sale",
      sellingPrice: 130,
      name: "Wool Coat",
      description: "Warm and stylish, like new.",
      quantity: 1,
      value: "78%",
      condition: "New",
      consignDuration: 28,
      status: "Available",
      shopAddress: "8 Coat St, Coatsville",
      startDate: "2024-01-08T00:00:00.000Z",
      endDate: "2024-02-08T00:00:00.000Z",
      consigner: "Hank Green",
      categoryName: "Clothing",
    },
    {
      itemId: "item-9",
      type: "For Auction",
      sellingPrice: 140,
      name: "Leather Belt",
      description: "Durable and stylish.",
      quantity: 2,
      value: "79%",
      condition: "Used",
      consignDuration: 29,
      status: "Available",
      shopAddress: "9 Belt Rd, Beltville",
      startDate: "2024-01-09T00:00:00.000Z",
      endDate: "2024-02-09T00:00:00.000Z",
      consigner: "Ivy Turner",
      categoryName: "Accessories",
    },
    {
      itemId: "item-10",
      type: "For Sale",
      sellingPrice: 150,
      name: "Denim Jeans",
      description: "Classic fit, brand new.",
      quantity: 3,
      value: "80%",
      condition: "New",
      consignDuration: 30,
      status: "Available",
      shopAddress: "10 Jean St, Denim City",
      startDate: "2024-01-10T00:00:00.000Z",
      endDate: "2024-02-10T00:00:00.000Z",
      consigner: "Jack White",
      categoryName: "Clothing",
    },
    {
      itemId: "item-11",
      type: "For Auction",
      sellingPrice: 160,
      name: "Cashmere Sweater",
      description: "Soft and warm, slightly used.",
      quantity: 1,
      value: "81%",
      condition: "Used",
      consignDuration: 31,
      status: "Available",
      shopAddress: "11 Sweater Ln, Cozy Town",
      startDate: "2024-01-11T00:00:00.000Z",
      endDate: "2024-02-11T00:00:00.000Z",
      consigner: "Kara Black",
      categoryName: "Clothing",
    },
    {
      itemId: "item-12",
      type: "For Sale",
      sellingPrice: 170,
      name: "Wool Gloves",
      description: "New and very warm.",
      quantity: 2,
      value: "82%",
      condition: "New",
      consignDuration: 32,
      status: "Available",
      shopAddress: "12 Glove St, Warmtown",
      startDate: "2024-01-12T00:00:00.000Z",
      endDate: "2024-02-12T00:00:00.000Z",
      consigner: "Liam Neeson",
      categoryName: "Accessories",
    },
    {
      itemId: "item-13",
      type: "For Auction",
      sellingPrice: 180,
      name: "Silk Tie",
      description: "Elegant and new.",
      quantity: 3,
      value: "83%",
      condition: "New",
      consignDuration: 33,
      status: "Available",
      shopAddress: "13 Tie Rd, Tieville",
      startDate: "2024-01-13T00:00:00.000Z",
      endDate: "2024-02-13T00:00:00.000Z",
      consigner: "Michael Scott",
      categoryName: "Accessories",
    },
  ],
};
export default newData;
